import type { Metadata } from "next";
import "./tokens.css";
import "./globals.css";
import "./modal.css";
import "./management.css";
import "./operations.css";
import "./portals.css";
import "./insights.css";
import "./login.css";
import "./login-actions.css";
import "./sessions.css";
import "./customer-detail.css";
import "./notifications.css";
import "./extensions.css";
import "./files.css";
import "./ui-actions.css";
import "./rewards.css";
import "./loyalty-automation.css";
import "./reward-builder.css";
import "./nfc-manager.css";
import "./campaigns.css";
import "./product-shell.css";
import "./dashboard-v2.css";
import "./platform-v2.css";
import "./mvp-settings.css";
import "./guest-portal.css";
import "./premium-wallet.css";
import "./guest-isolation.css";
import "./founder-upgrades.css";
import "./scanner.css";
import "./program-mechanics.css";
import "./product-simplified.css";
import "./simplified-overrides.css";
import "./provisioning-wizard.css";
import "./design-system-v3.css";
import "./app-shell-v4.css";
import "./modules-v4.css";
import "./experience-v4.css";
import "./loyalty-workbench-v5.css";
import "./design-system-v6.css";
import "./customer-app-v6.css";
import "./staff-mode-v8.css";
import "./overview-v9.css";
import "./reports.css";
import "./scanner-accessibility.css";
import "./customer-timeline.css";
import "./reward-lifecycle.css";
import "./guided-dashboard.css";
import "./analytics-outcomes.css";
import "./approval-workflow.css";
import "./risk-center.css";
import "./product-polish-v10.css";
import "./confirm-dialog.css";
import "./auth-gate.css";
import "./product-redesign-v11.css";

export const metadata: Metadata = { title: "Tappix — бизнес-панель", description: "Управление клиентами и программой лояльности" };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="ru"><body>{children}</body></html>;
}
