"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BarChart3, Check, CircleAlert, Gift, Nfc, RefreshCw, Sparkles, TrendingUp, Users } from "lucide-react";
import { api } from "@/lib/api";
import { SectionShell } from "@/components/section-shell";

type MetricSet={visits:number;customers:number;returning:number;rewards:number};
type DashboardData={period:{label:string;from:string;to:string};metrics:MetricSet;previous:MetricSet;loyalty:{repeatRate:number;redemptionRate:number;closeToReward:number;averageVisits:number};trend:{date:string;value:number}[];customers:number;onboarding:Record<string,boolean>};
type Branch={id:string;name:string};
const empty:DashboardData={period:{label:"30 дней",from:"",to:""},metrics:{visits:0,customers:0,returning:0,rewards:0},previous:{visits:0,customers:0,returning:0,rewards:0},loyalty:{repeatRate:0,redemptionRate:0,closeToReward:0,averageVisits:0},trend:[],customers:0,onboarding:{}};
const launchSteps=[["program","Бизнес и программа","/onboarding"],["reward","Награда","/loyalty"],["device","QR или NFC","/devices"],["testCustomer","Тестовый клиент","/scanner"],["launched","Запуск","/loyalty"]] as const;
function Comparison({current,previous}:{current:number;previous:number}){if(previous===0)return <span className="metric-comparison neutral">Недостаточно данных для сравнения</span>;const delta=(current-previous)/previous*100;return <span className={`metric-comparison ${delta>=0?"positive":"negative"}`}>{delta>=0?"+":""}{delta.toFixed(0)}% <small>к прошлому периоду</small></span>}

export default function Dashboard(){
 const[data,setData]=useState(empty),[branches,setBranches]=useState<Branch[]>([]),[period,setPeriod]=useState("30d"),[branch,setBranch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const[dashboard,branchItems]=await Promise.all([api<DashboardData>(`/dashboard?period=${period}&branch=${branch}`),branches.length?Promise.resolve(branches):api<Branch[]>("/branches")]);setData(dashboard);setBranches(branchItems)}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить обзор")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[period,branch]);
 const completed=launchSteps.filter(([key])=>data.onboarding[key]).length,launched=Boolean(data.onboarding.launched),max=Math.max(1,...data.trend.map(x=>x.value));
 const attention=useMemo(()=>[data.metrics.visits===0?{title:"Нет посещений за период",detail:"Откройте Staff Mode или проверьте QR-точку",href:"/scanner"}:null,data.loyalty.closeToReward>0?{title:`${data.loyalty.closeToReward} клиентов близки к награде`,detail:"Им осталось одно посещение",href:"/campaigns"}:null].filter(Boolean) as {title:string;detail:string;href:string}[],[data]);
 return <SectionShell active="/" title="Обзор" subtitle="Клиенты, повторные визиты и награды">
  <div className="dashboard-filterbar" aria-label="Фильтры обзора"><label>Период<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Сегодня</option><option value="7d">7 дней</option><option value="30d">30 дней</option><option value="month">Этот месяц</option></select></label><label>Филиал<select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">Все филиалы</option>{branches.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></div>
  {loading&&<div className="dashboard-skeleton" aria-busy="true" aria-label="Загружаем обзор">{Array.from({length:6},(_,i)=><i key={i}/>)}</div>}
  {error&&<div className="dashboard-load-error" role="alert"><CircleAlert/><span><strong>Не удалось обновить обзор</strong><small>Попробуйте ещё раз.</small></span><button onClick={()=>void load()}><RefreshCw/>Повторить</button></div>}
  {!loading&&!error&&<div className="owner-overview-layout">
   {!launched&&<section className="owner-launch-board"><div className="launch-board-title"><Sparkles/><div><small>ЗАПУСК TAPPIX</small><h2>Подготовьте программу к первому гостю</h2><p>{completed} из {launchSteps.length} шагов выполнено</p></div><strong>{completed}/{launchSteps.length}</strong></div><div className="launch-board-steps">{launchSteps.map(([key,label,href],i)=><Link href={href} className={data.onboarding[key]?"done":i===completed?"current":""} key={key}>{data.onboarding[key]?<Check/>:<b>{i+1}</b>}<span>{label}</span><ArrowRight/></Link>)}</div><Link className="primary-action guided-launch-link" href="/onboarding">Продолжить настройку <ArrowRight/></Link></section>}
   {launched&&<><section className="owner-overview-header"><div><small>{data.period.label.toLocaleUpperCase("ru-RU")}</small><h2>Программа работает</h2><p>Все показатели ниже используют одинаковые фильтры.</p></div><Link className="primary-action" href="/scanner"><Nfc/>Открыть Staff Mode</Link></section>
   <section className="owner-pulse">{[["ПОСЕЩЕНИЯ",data.metrics.visits,data.previous.visits],["НОВЫЕ КЛИЕНТЫ",data.metrics.customers,data.previous.customers],["ВОЗВРАЩАЮТСЯ",data.metrics.returning,data.previous.returning],["НАГРАДЫ",data.metrics.rewards,data.previous.rewards]].map(([label,current,previous])=><article key={String(label)}><small>{label}</small><strong>{Number(current).toLocaleString("ru-RU")}</strong><Comparison current={Number(current)} previous={Number(previous)}/></article>)}</section>
   <section className="owner-performance"><header><div><small>АКТИВНОСТЬ КЛИЕНТОВ</small><h3>Посещения по дням</h3><p>{data.period.label}</p></div><Link href="/analytics">Открыть аналитику <ArrowRight/></Link></header>{data.trend.some(x=>x.value>0)?<div className="owner-trend-bars">{data.trend.map(x=><div key={x.date}><i style={{height:`${Math.max(8,x.value/max*100)}%`}}><b>{x.value}</b></i><small>{new Date(x.date).toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}</small></div>)}</div>:<div className="owner-empty-trend"><BarChart3/><strong>За этот период посещений нет</strong><Link href="/scanner">Открыть Staff Mode</Link></div>}</section>
   <section className="loyalty-performance"><header><div><small>ЛОЯЛЬНОСТЬ</small><h3>Как клиенты возвращаются</h3></div><Gift/></header><div><article><strong>{data.loyalty.repeatRate.toFixed(0)}%</strong><span>Повторные клиенты</span></article><article><strong>{data.loyalty.redemptionRate.toFixed(0)}%</strong><span>Наград использовано</span></article><article><strong>{data.loyalty.closeToReward}</strong><span>Близко к награде</span></article><article><strong>{data.loyalty.averageVisits.toFixed(1)}</strong><span>Среднее визитов</span></article></div></section>
   <div className="owner-overview-columns"><section className="owner-attention"><header><CircleAlert/><div><small>ТРЕБУЕТ ВНИМАНИЯ</small><h3>{attention.length?`${attention.length} действия`:"Всё под контролем"}</h3></div></header>{attention.length?attention.map(x=><Link href={x.href} key={x.title}><span><strong>{x.title}</strong><small>{x.detail}</small></span><ArrowRight/></Link>):<p>Критичных сигналов по выбранному периоду нет.</p>}</section><section className="owner-next-actions"><header><small>РЕКОМЕНДАЦИИ ПО ДАННЫМ</small><h3>{data.loyalty.closeToReward?"Верните близких к награде":"Продолжайте собирать данные"}</h3></header>{data.loyalty.closeToReward>0?<Link href="/campaigns"><TrendingUp/><span><strong>Создать кампанию</strong><small>Аудитория рассчитана по прогрессу</small></span><ArrowRight/></Link>:<Link href="/customers"><Users/><span><strong>Открыть клиентов</strong><small>Посмотреть сегменты и прогресс</small></span><ArrowRight/></Link>}</section></div></>}
  </div>}
 </SectionShell>
}
