"use client";
import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";
import { AlertTriangle, ArrowRight, BarChart3, Check, CircleDot, Gift, Lightbulb, Nfc, Plus, Sparkles, UserPlus, Users, X } from "lucide-react";
import { api } from "@/lib/api";
import { SectionShell } from "@/components/section-shell";

type DashboardData = { customers:number; visitsToday:number; bonusIssued:number; bonusRedeemed:number; registrations:number; nfcConversion:number; latestCustomers:{id:string;name:string;phone:string;points:number;createdAt:string}[]; latestVisits:{id:string;customer:string;branch:string;points:number;createdAt:string}[]; onboarding:Record<string,boolean> };
type Customer = { id:string; firstName:string; lastName:string; phone:string };
type Branch = { id:string; name:string };
type Action = "customer"|"visit"|"bonus"|"nfc"|null;
const empty:DashboardData={customers:0,visitsToday:0,bonusIssued:0,bonusRedeemed:0,registrations:0,nfcConversion:0,latestCustomers:[],latestVisits:[],onboarding:{}};

export default function Dashboard(){
 const[data,setData]=useState(empty),[customers,setCustomers]=useState<Customer[]>([]),[branches,setBranches]=useState<Branch[]>([]),[action,setAction]=useState<Action>(null),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[customerQuery,setCustomerQuery]=useState(""),[searching,setSearching]=useState(false),[dirty,setDirty]=useState(false);
 const actionTrigger=useRef<HTMLButtonElement|null>(null);
 async function load(){try{const[d,b]=await Promise.all([api<DashboardData>("/dashboard"),api<Branch[]>("/branches")]);setData(d);setBranches(b)}catch(e){setMessage(e instanceof Error?e.message:"Не удалось загрузить обзор")}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(action!=="visit"&&action!=="bonus")return;if(customerQuery.trim().length<2){setCustomers([]);setSearching(false);return}setSearching(true);const timer=window.setTimeout(()=>{api<{items:Customer[]}>(`/customers?limit=10&search=${encodeURIComponent(customerQuery.trim())}`).then(result=>setCustomers(result.items)).catch(error=>setMessage(error.message)).finally(()=>setSearching(false))},300);return()=>window.clearTimeout(timer)},[action,customerQuery]);
 useEffect(()=>{if(!action)return;function closeOnEscape(event:KeyboardEvent){if(event.key==="Escape")requestClose()}window.addEventListener("keydown",closeOnEscape);return()=>window.removeEventListener("keydown",closeOnEscape)},[action,dirty]);
 function openAction(next:Exclude<Action,null>,trigger:HTMLButtonElement){actionTrigger.current=trigger;setCustomerQuery("");setCustomers([]);setDirty(false);setAction(next)}
 function requestClose(){if(dirty&&!confirm("Закрыть форму? Введённые данные не сохранятся."))return;setAction(null);setDirty(false);requestAnimationFrame(()=>actionTrigger.current?.focus())}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const form=Object.fromEntries(new FormData(e.currentTarget));try{
   if(action==="customer"){const digits=String(form.phone||"").replace(/\D/g,"");form.phone=digits.length===11&&digits.startsWith("8")?`+7${digits.slice(1)}`:digits.length===11?`+${digits}`:String(form.phone||"").trim();await api("/customers",{method:"POST",body:JSON.stringify(form)})}
   if(action==="visit")await api("/visits",{method:"POST",body:JSON.stringify(form)});
   if(action==="bonus")await api(`/customers/${form.customerId}/bonus`,{method:"POST",body:JSON.stringify({operation:"credit",amount:Number(form.amount),description:form.description})});
   if(action==="nfc")await api("/devices",{method:"POST",body:JSON.stringify({...form,kind:"nfc",destination:"join"})});
   setAction(null);setDirty(false);setMessage("Действие выполнено");await load();requestAnimationFrame(()=>actionTrigger.current?.focus());
 }catch(error){setMessage(error instanceof Error?error.message:"Не удалось выполнить действие")}finally{setSaving(false)}}
 const steps=[['company','Компания настроена','/settings'],['branch','Добавьте филиал','/branches'],['team','Пригласите сотрудника','/employees'],['device','Активируйте NFC','/devices'],['firstCustomer','Получите первого клиента','/customers']] as const;
 const completed=steps.filter(([key])=>data.onboarding[key]).length;
 const metrics=[['Клиенты',data.customers,'Всего в базе'],['Посещения сегодня',data.visitsToday,'Активность программы'],['Оборот бонусов',data.bonusIssued+data.bonusRedeemed,`${data.bonusIssued} начислено · ${data.bonusRedeemed} списано`],['NFC-конверсия',`${Math.min(data.nfcConversion,100).toFixed(1)}%`,'Касание → регистрация']];
 const activity=Array.from({length:7},(_,index)=>{const date=new Date();date.setDate(date.getDate()-(6-index));const key=date.toISOString().slice(0,10);return{label:date.toLocaleDateString("ru-RU",{weekday:"short"}),value:data.latestVisits.filter(item=>item.createdAt.slice(0,10)===key).length}});
 const maxActivity=Math.max(1,...activity.map(item=>item.value));
 const attention=[completed<steps.length&&{title:"Завершите запуск программы",text:`Осталось ${steps.length-completed} шага`,href:"/onboarding"},data.visitsToday===0&&{title:"Сегодня ещё нет посещений",text:"Откройте Staff Mode и отметьте первого гостя",href:"/scanner"},data.nfcConversion<20&&{title:"Можно улучшить NFC-конверсию",text:"Проверьте расположение NFC и QR у кассы",href:"/devices"}].filter(Boolean) as {title:string;text:string;href:string}[];
 return <SectionShell active="/" title="Обзор" subtitle="Главное о вашей программе лояльности сегодня">
   {message&&<div className="v2-notice" role="status">{message}</div>}
   <div className="v2-hero"><div><span>Сегодня</span><h2>Всё готово для следующего гостя</h2><p>Сканируйте карту, отмечайте визит — Tappix сам обновит бонусы, штампы или скидку.</p></div><Link className="dashboard-scan" href="/scanner"><Nfc/>Открыть сканер</Link></div>
   {completed<steps.length&&<section className="onboarding-card"><div className="onboarding-head"><div><span><Sparkles/></span><div><h2>Запустите Tappix</h2><p>{completed} из {steps.length} шагов выполнено</p></div></div><Link className="guided-launch-link" href="/onboarding">Запустить мастер<ArrowRight/></Link></div><div className="progress"><i style={{width:`${completed/steps.length*100}%`}}/></div><div className="onboarding-steps">{steps.map(([key,label,href])=><Link className={data.onboarding[key]?"done":""} href={href} key={key}>{data.onboarding[key]?<Check/>:<CircleDot/>}<span>{label}</span><ArrowRight/></Link>)}</div></section>}
   <div className="v2-metrics">{metrics.map(([label,value,help],index)=><article key={label}><span>{index+1}</span><p>{label}</p><strong>{value}</strong><small>{help}</small></article>)}</div>
   <div className="dashboard-decision-grid"><section className="dashboard-result"><header><div><span><BarChart3/></span><div><h2>Результат за 7 дней</h2><p>Посещения по дням на основе последних операций</p></div></div><Link href="/analytics">Подробнее <ArrowRight/></Link></header><div className="dashboard-bars" role="img" aria-label="Посещения за последние семь дней">{activity.map(item=><div key={item.label}><i style={{height:`${Math.max(8,item.value/maxActivity*100)}%`}}><b>{item.value}</b></i><small>{item.label}</small></div>)}</div></section><aside className="dashboard-attention"><header><AlertTriangle/><div><h2>Требует внимания</h2><p>{attention.length?`${attention.length} рекомендации на сегодня`:"Критичных задач нет"}</p></div></header><div>{attention.length?attention.slice(0,3).map(item=><Link href={item.href} key={item.title}><span><strong>{item.title}</strong><small>{item.text}</small></span><ArrowRight/></Link>):<div className="attention-clear"><Check/><span><strong>Всё под контролем</strong><small>Программа работает штатно</small></span></div>}</div></aside></div>
   <section className="quick-card"><div><h2>Быстрые действия</h2><p>Три действия для ежедневной работы</p></div><div className="quick-actions"><button onClick={event=>openAction("customer",event.currentTarget)}><UserPlus/><span><strong>Создать клиента</strong><small>Добавить в CRM</small></span></button><button onClick={event=>openAction("visit",event.currentTarget)}><Users/><span><strong>Добавить посещение</strong><small>Начислить автоматически</small></span></button><button onClick={event=>openAction("bonus",event.currentTarget)}><Gift/><span><strong>Начислить бонусы</strong><small>Указать причину операции</small></span></button></div><footer><Lightbulb/><span><strong>Совет</strong> Используйте Staff Mode у кассы — сотруднику не нужна полная бизнес-панель.</span><Link href="/scanner">Открыть</Link></footer></section>
   <div className="v2-feed-grid"><section className="feed-card"><div className="feed-head"><h2>Последние регистрации</h2><Link href="/customers">Все клиенты</Link></div>{data.latestCustomers.length?data.latestCustomers.map(x=><Link href={`/customers/${x.id}`} className="feed-row" key={x.id}><span>{x.name.slice(0,1)}</span><div><strong>{x.name}</strong><small>{x.phone}</small></div><time>{new Date(x.createdAt).toLocaleDateString("ru-RU")}</time></Link>):<div className="feed-empty">Пока нет регистраций</div>}</section><section className="feed-card"><div className="feed-head"><h2>Последние посещения</h2><Link href="/analytics">Аналитика</Link></div>{data.latestVisits.length?data.latestVisits.map(x=><div className="feed-row" key={x.id}><span><Check/></span><div><strong>{x.customer}</strong><small>{x.branch} · +{x.points} бонусов</small></div><time>{new Date(x.createdAt).toLocaleDateString("ru-RU")}</time></div>):<div className="feed-empty">Пока нет посещений</div>}</section></div>
   {action&&<div className="v2-dialog-backdrop" onMouseDown={requestClose}><div className="v2-dialog" role="dialog" aria-modal="true" aria-labelledby="quick-title" onMouseDown={e=>e.stopPropagation()}><header><div><h2 id="quick-title">{{customer:"Новый клиент",visit:"Добавить посещение",bonus:"Начислить бонусы",nfc:"Создать NFC"}[action]}</h2><p>Заполните данные и подтвердите действие.</p></div><button aria-label="Закрыть" onClick={requestClose}><X/></button></header><form onSubmit={submit} onChange={()=>setDirty(true)}>
    {action==="customer"&&<><label>Имя<input name="firstName" required autoFocus/></label><label>Фамилия<input name="lastName"/></label><label>Телефон<input name="phone" type="tel" required placeholder="+7 700 000 00 00"/></label><label>Email<input name="email" type="email"/></label></>}
    {(action==="visit"||action==="bonus")&&<><label>Найти клиента<input value={customerQuery} onChange={event=>setCustomerQuery(event.target.value)} placeholder="Имя или номер телефона" autoComplete="off" autoFocus/><small className="field-help">{searching?"Ищем…":customerQuery.length<2?"Введите минимум 2 символа":customers.length?`Найдено: ${customers.length}`:"Клиенты не найдены"}</small></label><label>Клиент<select name="customerId" required disabled={searching||!customers.length}><option value="">Выберите из результатов</option>{customers.map(x=><option value={x.id} key={x.id}>{x.firstName} {x.lastName} · {x.phone}</option>)}</select></label></>}
    {action==="visit"&&<><label>Филиал<select name="branchId" required><option value="">Выберите филиал</option>{branches.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Комментарий<textarea name="comment" rows={3}/></label></>}
    {action==="bonus"&&<><label>Количество<input name="amount" type="number" min="1" required/></label><label>Причина ручного начисления<input name="description" required placeholder="Например, компенсация за задержку"/><small className="field-help">Причина сохранится в истории операций.</small></label></>}
    {action==="nfc"&&<><label>Название<input name="name" required autoFocus placeholder="Стойка ресепшн"/></label><label>Филиал<select name="branchId" required><option value="">Выберите филиал</option>{branches.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></>}
    <div className="v2-dialog-actions"><button type="button" onClick={requestClose}>Отмена</button><button className="primary" disabled={saving}>{saving?"Сохраняем…":"Подтвердить"}</button></div></form></div></div>}
 </SectionShell>
}
