"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, Check, CircleAlert, Nfc, RefreshCw, Sparkles, UserPlus, Users } from "lucide-react";
import { api } from "@/lib/api";
import { SectionShell } from "@/components/section-shell";
type DashboardData={customers:number;visitsToday:number;bonusIssued:number;bonusRedeemed:number;registrations:number;repeatCustomers:number;rewardsIssued:number;nfcConversion:number;latestCustomers:{id:string;name:string;phone:string;points:number;createdAt:string}[];latestVisits:{id:string;customer:string;branch:string;points:number;createdAt:string}[];onboarding:Record<string,boolean>};
type Branch={id:string;name:string};
const empty:DashboardData={customers:0,visitsToday:0,bonusIssued:0,bonusRedeemed:0,registrations:0,repeatCustomers:0,rewardsIssued:0,nfcConversion:0,latestCustomers:[],latestVisits:[],onboarding:{}};
const launchSteps=[['program','Создать программу','/onboarding'],['reward','Настроить награду','/loyalty'],['device','Добавить QR или NFC','/devices'],['testCustomer','Провести тестовый визит','/scanner'],['launched','Запустить','/loyalty']] as const;
export default function Dashboard(){
 const [data,setData]=useState(empty),[branches,setBranches]=useState<Branch[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const [dashboard,branchItems]=await Promise.all([api<DashboardData>("/dashboard"),api<Branch[]>("/branches")]);setData(dashboard);setBranches(branchItems)}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить обзор")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const completed=launchSteps.filter(([key])=>data.onboarding[key]).length,launched=completed===launchSteps.length;
 const recentDays=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-(6-i));const key=date.toISOString().slice(0,10);return {label:date.toLocaleDateString("ru-RU",{weekday:"short"}),value:data.latestVisits.filter(v=>v.createdAt.slice(0,10)===key).length}}),max=Math.max(1,...recentDays.map(x=>x.value));
 const attention=[data.visitsToday===0?{title:"Проведите первый визит",detail:"Откройте рабочее место сотрудника",href:"/scanner"}:null,data.nfcConversion<20?{title:"Проверьте точку регистрации",detail:"QR и NFC должны быть рядом с кассой",href:"/devices"}:null].filter(Boolean) as {title:string;detail:string;href:string}[];
 return <SectionShell active="/" title="Обзор" subtitle="Решения для бизнеса на сегодня">
  {loading&&<div className="dashboard-loading" aria-busy="true"><i/><i/><i/></div>}{error&&<div className="dashboard-load-error" role="alert"><CircleAlert/><span>{error}</span><button onClick={()=>void load()}><RefreshCw/>Повторить</button></div>}
  {!loading&&!error&&<div className="owner-overview-layout"><header className="owner-overview-header"><div><small>СЕГОДНЯ · {branches[0]?.name||"ВАШ БИЗНЕС"}</small><h2>{launched?"Программа работает":"Соберите программу до первого гостя"}</h2><p>{launched?"Здесь видно, что изменилось и какое действие принесёт следующий результат.":`${completed} из ${launchSteps.length} шагов завершено`}</p></div><Link className="primary-action" href={launched?"/scanner":"/onboarding"}>{launched?<><Nfc/>Открыть Staff Mode</>:<>Продолжить запуск<ArrowRight/></>}</Link></header>
   {!launched&&<section className="owner-launch-board"><div className="launch-board-title"><Sparkles/><div><small>ПУТЬ ЗАПУСКА</small><h3>До первых результатов</h3></div><strong>{completed}/{launchSteps.length}</strong></div><div className="launch-board-steps">{launchSteps.map(([key,label,href],i)=><Link href={href} className={data.onboarding[key]?"done":i===completed?"current":""} key={key}>{data.onboarding[key]?<Check/>:<b>{i+1}</b>}<span>{label}</span><ArrowRight/></Link>)}</div></section>}
   {launched&&<><section className="owner-pulse"><article><small>КЛИЕНТЫ</small><strong>{data.customers}</strong><span>всего в программе</span></article><article><small>ПОСЕЩЕНИЯ</small><strong>{data.visitsToday}</strong><span>сегодня</span></article><article><small>ВОЗВРАЩАЮТСЯ</small><strong>{data.repeatCustomers}</strong><span>повторных клиентов</span></article><article><small>НАГРАДЫ</small><strong>{data.rewardsIssued}</strong><span>выдано клиентам</span></article></section><section className="owner-performance"><header><div><small>ГЛАВНЫЙ СИГНАЛ</small><h3>Активность клиентов</h3><p>Посещения за последние семь дней</p></div><Link href="/analytics">Разобрать результат <ArrowRight/></Link></header>{recentDays.some(x=>x.value>0)?<div className="owner-trend-bars">{recentDays.map(x=><div key={x.label}><i style={{height:`${Math.max(8,x.value/max*100)}%`}}><b>{x.value}</b></i><small>{x.label}</small></div>)}</div>:<div className="owner-empty-trend"><BarChart3/><strong>Данные появятся после первого визита</strong><Link href="/scanner">Открыть Staff Mode</Link></div>}</section><div className="owner-overview-columns"><section className="owner-attention"><header><CircleAlert/><div><small>ТРЕБУЕТ ВНИМАНИЯ</small><h3>{attention.length?`${attention.length} действия сегодня`:"Всё под контролем"}</h3></div></header>{attention.length?attention.map(item=><Link href={item.href} key={item.title}><span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowRight/></Link>):<p>Критичных задач нет. Продолжайте отмечать визиты.</p>}</section><section className="owner-next-actions"><header><small>СЛЕДУЮЩИЙ ШАГ</small><h3>Быстрые действия</h3></header><Link href="/scanner"><Nfc/><span><strong>Обслужить клиента</strong><small>Сканировать QR или код</small></span><ArrowRight/></Link><Link href="/customers"><Users/><span><strong>Открыть клиентов</strong><small>Посмотреть прогресс и сегменты</small></span><ArrowRight/></Link><Link href="/customers"><UserPlus/><span><strong>Добавить клиента</strong><small>Создать профиль вручную</small></span><ArrowRight/></Link></section></div></>}
  </div>}
 </SectionShell>;
}
