"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowUpRight, BarChart3, CalendarHeart, CheckCircle2, CircleAlert, Clock3, Info, Mail, MessageCircle, Play, Plus, Send, Sparkles, ToggleLeft, ToggleRight, TrendingUp, UserRoundX, Users, WalletCards, X } from "lucide-react";
import { api } from "@/lib/api";
import { SectionShell } from "./section-shell";

type Campaign = { id:string;name:string;subject:string;segment:string;status:string;audienceCount:number;sentCount:number;failedCount:number;messageCost:number;rewardCost:number;attributionWindowDays:number;holdoutPercent:number;createdAt:string };
type Automation = { id:string;triggerType:string;name:string;channel:"email"|"whatsapp";subject:string;message:string;settings:Record<string,unknown>;active:boolean;runs:number;sent:number;failed:number };
type Draft = { name:string;segment:string;inactiveDays:number;level:string;subject:string;body:string;messageCost:number;rewardCost:number;attributionWindowDays:number;holdoutPercent:number };
type CampaignAnalytics={name:string;status:string;attributionWindowDays:number;holdoutPercent:number;upliftAvailable:boolean;audience:{treatment:number;holdout:number};delivery:{delivered:number;opened:number;clicked:number;openRate:number;clickRate:number};purchases:{treatmentBuyers:number;treatmentRevenue:number;holdoutBuyers:number;holdoutRevenue:number;treatmentConversionRate:number;holdoutConversionRate:number;attributedRevenue:number;incrementalRevenue:number|null;upliftPercentagePoints:number|null};costs:{messages:number;rewards:number;total:number};roi:number|null;roiRevenueBasis:string};

const emptyDraft:Draft={name:"",segment:"all",inactiveDays:30,level:"basic",subject:"",body:"",messageCost:15,rewardCost:0,attributionWindowDays:7,holdoutPercent:10};
const templates:[string,string,string,Draft][]=[
  ["Вернуть гостей","Не были 30 дней","winback",{...emptyDraft,name:"Возвращаем клиентов",segment:"inactive",subject:"Мы скучаем по вам",body:"Здравствуйте, {{name}}! Вас давно не было. Возвращайтесь — для вас действует персональное предложение."}],
  ["Поздравить","День рождения","birthday",{...emptyDraft,name:"День рождения",segment:"birthday",subject:"С днём рождения!",body:"{{name}}, поздравляем! Для вас приготовлен подарок — используйте его при следующем визите.",rewardCost:100}],
  ["Наградить VIP","Постоянные гости","vip",{...emptyDraft,name:"Предложение для VIP",segment:"level",level:"vip",subject:"Особое предложение для вас",body:"{{name}}, спасибо, что выбираете нас. Для вас доступна специальная награда.",rewardCost:200}],
];
const automationMeta:Record<string,{icon:typeof CalendarHeart;description:string}>={
  birthday_bonus:{icon:CalendarHeart,description:"Начисляет бонус и поздравляет клиента в день рождения"},
  bonus_expiry_3d:{icon:Clock3,description:"Предупреждает за 3 дня до сгорания бонусов"},
  winback_30d:{icon:UserRoundX,description:"Возвращает клиентов, которых не было 30 дней"},
};

export function CampaignsPage(){
  const [items,setItems]=useState<Campaign[]>([]),[automations,setAutomations]=useState<Automation[]>([]),[tab,setTab]=useState<"campaigns"|"automations">("campaigns"),[open,setOpen]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft),[analytics,setAnalytics]=useState<CampaignAnalytics|null>(null),[analyticsLoading,setAnalyticsLoading]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[running,setRunning]=useState(false),[preview,setPreview]=useState<{id:string;total:number}|null>(null);
  async function load(){setLoading(true);setError("");const [campaignResult,automationResult]=await Promise.allSettled([api<Campaign[]>("/campaigns"),api<Automation[]>("/campaign-automations")]);if(campaignResult.status==="fulfilled")setItems(campaignResult.value);else setError(campaignResult.reason instanceof Error?campaignResult.reason.message:"Не удалось загрузить кампании");if(automationResult.status==="fulfilled")setAutomations(automationResult.value);setLoading(false)}
  useEffect(()=>{void load()},[]);
  function start(next:Draft=emptyDraft){setDraft(next);setOpen(true);setMsg("")}
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMsg("");try{const data=Object.fromEntries(new FormData(e.currentTarget));const result=await api<{id:string}>("/campaigns",{method:"POST",body:JSON.stringify({...data,inactiveDays:Number(data.inactiveDays),messageCost:Number(data.messageCost),rewardCost:Number(data.rewardCost),attributionWindowDays:Number(data.attributionWindowDays),holdoutPercent:Number(data.holdoutPercent)})});const audience=await api<{total:number}>(`/campaigns/${result.id}/preview`);setOpen(false);setPreview({id:result.id,total:audience.total});setMsg(`Черновик готов: ${audience.total} получателей`);await load()}catch(requestError){setMsg(requestError instanceof Error?requestError.message:"Не удалось создать кампанию")}finally{setSaving(false)}}
  async function send(id:string,total?:number){if(!confirm(`Отправить кампанию ${total!==undefined?`${total} клиентам`:"выбранной аудитории"}?`))return;setSaving(true);try{const result=await api<{sent:number;failed:number}>(`/campaigns/${id}/send`,{method:"POST",body:"{}"});setPreview(null);setMsg(`Отправлено: ${result.sent}. Ошибок: ${result.failed}`);await load()}catch(requestError){setMsg(requestError instanceof Error?requestError.message:"Ошибка отправки")}finally{setSaving(false)}}
  async function toggle(item:Automation){setAutomations(current=>current.map(value=>value.id===item.id?{...value,active:!value.active}:value));try{await api(`/campaign-automations/${item.id}`,{method:"PATCH",body:JSON.stringify({channel:item.channel,subject:item.subject,message:item.message,settings:item.settings,active:!item.active})});setMsg(`${item.name}: ${item.active?"выключено":"включено"}`)}catch(requestError){setAutomations(current=>current.map(value=>value.id===item.id?item:value));setMsg(requestError instanceof Error?requestError.message:"Не удалось изменить автоматизацию")}}
  async function runAutomations(){setRunning(true);try{const result=await api<{birthdayBonuses:number;messagesSent:number}>("/campaign-automations/run",{method:"POST",body:"{}"});setMsg(`Проверка завершена: ${result.birthdayBonuses} бонусов, ${result.messagesSent} сообщений`);await load()}catch(requestError){setMsg(requestError instanceof Error?requestError.message:"Не удалось запустить проверку")}finally{setRunning(false)}}
  async function showAnalytics(id:string){setAnalyticsLoading(true);try{setAnalytics(await api<CampaignAnalytics>(`/campaigns/${id}/analytics`))}catch(requestError){setMsg(requestError instanceof Error?requestError.message:"Не удалось загрузить результаты кампании")}finally{setAnalyticsLoading(false)}}
  const money=(value:number|null|undefined)=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"KZT",maximumFractionDigits:0}).format(value||0);
  return <SectionShell active="/campaigns" title="Кампании" subtitle="Разовые рассылки и автоматические сценарии">
    {msg&&<div className="notice" role="status">{msg}</div>}{error&&<div className="crm-error" role="alert"><span><Mail/><strong>Не удалось загрузить кампании</strong><small>{error}</small></span><button onClick={()=>void load()}>Повторить</button></div>}
    <section className="campaign-intro"><div><span><Sparkles/></span><div><small>ЦЕНТР КОММУНИКАЦИЙ</small><h2>Возвращайте клиентов вовремя</h2><p>Запустите готовую рассылку или включите сценарий, который работает автоматически.</p></div></div><button onClick={()=>start()}><Plus/>Новая рассылка</button></section>
    <nav className="campaign-tabs" aria-label="Разделы кампаний"><button className={tab==="campaigns"?"current":""} aria-pressed={tab==="campaigns"} onClick={()=>setTab("campaigns")}><Send/>Рассылки <span>{items.length}</span></button><button className={tab==="automations"?"current":""} aria-pressed={tab==="automations"} onClick={()=>setTab("automations")}><Sparkles/>Автоматизация <span>{automations.filter(x=>x.active).length}</span></button></nav>
    {tab==="campaigns"&&<>
      <section className="campaign-templates"><header><h2>Быстрый старт</h2><p>Выберите цель — текст и аудитория уже подготовлены.</p></header><div>{templates.map(([title,description,key,value])=><button onClick={()=>start(value)} key={key}><span>{key==="birthday"?<CalendarHeart/>:key==="vip"?<Users/>:<UserRoundX/>}</span><strong>{title}</strong><small>{description}</small><Plus/></button>)}</div></section>
      {preview&&<section className="campaign-ready"><Users/><div><strong>Кампания готова к отправке</strong><p>{preview.total?`${preview.total} клиентов с заполненным Email`:"В выбранной аудитории пока нет клиентов с Email"}</p></div><button disabled={!preview.total||saving} onClick={()=>void send(preview.id,preview.total)}><Send/>{saving?"Отправляем…":"Отправить"}</button></section>}
      <div className={`campaign-grid ${loading?"is-loading":""}`}>{loading?Array.from({length:3},(_,index)=><article className="campaign-skeleton" key={index}/>):items.map(x=><article key={x.id}><span><Mail/></span><div><h2>{x.name}</h2><p>{x.subject}</p><small>{x.segment} · {new Date(x.createdAt).toLocaleDateString("ru-RU")}</small></div><div className="campaign-stats"><b>{x.sentCount}/{x.audienceCount}</b><span className={x.status==="sent"?"mail-sent":"tag"}>{x.status==="sent"?"Отправлена":"Черновик"}</span></div>{x.status==="draft"?<button disabled={saving} onClick={async()=>{const audience=await api<{total:number}>(`/campaigns/${x.id}/preview`);void send(x.id,audience.total)}}>Отправить</button>:<button className="campaign-results-button" disabled={analyticsLoading} onClick={()=>void showAnalytics(x.id)}><BarChart3/>Результаты</button>}</article>)}{!loading&&!items.length&&<div className="campaign-empty"><span><Mail/></span><h2>Создайте первую рассылку</h2><p>Начните с готового шаблона выше — останется проверить текст и получателей.</p><button onClick={()=>start(templates[0][3])}><Plus/>Создать за минуту</button></div>}</div>
    </>}
    {tab==="automations"&&<section className="automation-center"><header><div><h2>Триггерные сценарии</h2><p>Система ежедневно проверяет условия и отправляет сообщение в нужный момент.</p></div><button disabled={running} onClick={()=>void runAutomations()}><Play/>{running?"Проверяем…":"Проверить сейчас"}</button></header><div>{automations.map(item=>{const meta=automationMeta[item.triggerType]||automationMeta.winback_30d;const Icon=meta.icon;return <article className={item.active?"active":""} key={item.id}><span><Icon/></span><div><small>{item.channel==="whatsapp"?<><MessageCircle/>WhatsApp</>:<><Mail/>Email</>}</small><h3>{item.name}</h3><p>{meta.description}</p><footer><b>{item.sent} отправлено</b>{item.failed>0&&<em>{item.failed} ошибок</em>}</footer></div><button className="automation-toggle" aria-label={`${item.active?"Выключить":"Включить"} ${item.name}`} aria-pressed={item.active} onClick={()=>void toggle(item)}>{item.active?<ToggleRight/>:<ToggleLeft/>}<span>{item.active?"Работает":"Выключено"}</span></button></article>})}</div></section>}
    {analytics&&<div className="sheet-bg campaign-analytics-bg" onMouseDown={event=>{if(event.target===event.currentTarget)setAnalytics(null)}}><section className="sheet campaign-analytics-sheet"><header><div><small>РЕЗУЛЬТАТЫ КАМПАНИИ</small><h2>{analytics.name}</h2><p>Окно атрибуции: {analytics.attributionWindowDays} дней</p></div><button aria-label="Закрыть" onClick={()=>setAnalytics(null)}><X/></button></header><div className="campaign-roi-hero"><span><TrendingUp/></span><div><small>{analytics.upliftAvailable?"ИНКРЕМЕНТАЛЬНАЯ ВЫРУЧКА":"АТРИБУТИРОВАННАЯ ВЫРУЧКА"}</small><strong>{money(analytics.upliftAvailable?analytics.purchases.incrementalRevenue:analytics.purchases.attributedRevenue)}</strong><p>{analytics.roi===null?"Добавьте стоимость сообщений для расчёта ROI":`ROI ${analytics.roi>=0?"+":""}${analytics.roi.toFixed(1)}%`}</p></div><b className={analytics.roi!==null&&analytics.roi>=0?"positive":""}>{analytics.roi!==null&&analytics.roi>=0?<ArrowUpRight/>:<WalletCards/>}</b></div><div className="campaign-metric-grid"><article><small>Доставлено</small><strong>{analytics.delivery.delivered}</strong><span>{analytics.delivery.openRate.toFixed(1)}% открытий</span></article><article><small>Переходы</small><strong>{analytics.delivery.clicked}</strong><span>{analytics.delivery.clickRate.toFixed(1)}% CTR</span></article><article><small>Покупатели</small><strong>{analytics.purchases.treatmentBuyers}</strong><span>{analytics.purchases.treatmentConversionRate?.toFixed?.(1)||0}% конверсия</span></article><article><small>Расходы</small><strong>{money(analytics.costs.total)}</strong><span>Сообщения + награды</span></article></div>{analytics.upliftAvailable?<section className="holdout-result"><CheckCircle2/><div><strong>Uplift подтверждён контрольной группой</strong><p>Основная группа: {analytics.audience.treatment} · Holdout: {analytics.audience.holdout} · прирост: {analytics.purchases.upliftPercentagePoints?.toFixed(1)} п.п.</p></div></section>:<section className="holdout-result attribution"><Info/><div><strong>Показана атрибутированная выручка</strong><p>Контрольная группа не создавалась. Называть эту выручку дополнительной некорректно.</p></div></section>}<section className="campaign-cost-breakdown"><h3>Экономика</h3><div><span>Стоимость сообщений <b>{money(analytics.costs.messages)}</b></span><span>Стоимость наград <b>{money(analytics.costs.rewards)}</b></span><span>Выручка основной группы <b>{money(analytics.purchases.treatmentRevenue)}</b></span></div></section></section></div>}
    {open&&<div className="sheet-bg" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)setOpen(false)}}><form key={`${draft.name}-${draft.segment}`} className="sheet campaign-form" onSubmit={create}><header><small>НОВАЯ РАССЫЛКА</small><h2>Проверьте кампанию</h2><p>Сначала сохранится черновик и покажется точное число получателей.</p></header><label>Название<input name="name" defaultValue={draft.name} required autoFocus/></label><label>Аудитория<select name="segment" defaultValue={draft.segment} required><option value="all">Все клиенты с Email</option><option value="inactive">Неактивные клиенты</option><option value="birthday">Дни рождения в этом месяце</option><option value="level">Определённый уровень</option></select></label><div className="campaign-form-row"><label>Неактивность, дней<input name="inactiveDays" type="number" min="1" defaultValue={draft.inactiveDays}/></label><label>Уровень<select name="level" defaultValue={draft.level}><option value="basic">Basic</option><option value="silver">Silver</option><option value="gold">Gold</option><option value="vip">VIP</option></select></label></div><fieldset className="campaign-economics"><legend>Экономика и эксперимент</legend><div className="campaign-form-row"><label>Цена сообщения, ₸<input name="messageCost" type="number" min="0" step="0.01" defaultValue={draft.messageCost}/></label><label>Стоимость награды, ₸<input name="rewardCost" type="number" min="0" step="0.01" defaultValue={draft.rewardCost}/></label></div><div className="campaign-form-row"><label>Окно атрибуции, дней<input name="attributionWindowDays" type="number" min="1" max="90" defaultValue={draft.attributionWindowDays}/></label><label>Контрольная группа<select name="holdoutPercent" defaultValue={draft.holdoutPercent}><option value="0">Без holdout</option><option value="5">5%</option><option value="10">10% — рекомендуется</option></select></label></div><small><Info/>Holdout не получит сообщение и позволит посчитать реальный uplift.</small></fieldset><label>Тема письма<input name="subject" defaultValue={draft.subject} required/></label><label>Сообщение<textarea name="body" rows={6} defaultValue={draft.body} required/><small>Переменная {"{{name}}"} автоматически заменится именем клиента.</small></label><div><button type="button" disabled={saving} onClick={()=>setOpen(false)}>Отмена</button><button className="primary-action" disabled={saving}>{saving?"Проверяем…":"Создать черновик"}</button></div></form></div>}
  </SectionShell>
}
