"use client";
import { FormEvent, useEffect, useState } from "react";
import { Check, ChevronRight, Clock3, Gift, Sparkles, Star, WalletCards } from "lucide-react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { csrfHeaders } from "@/lib/csrf";
const base=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8080/api/v1";
type PortalConfig={welcomeTitle?:string;welcomeText?:string;primaryColor?:string;backgroundUrl?:string;logoUrl?:string;requireEmail?:boolean;requireCity?:boolean;showGender?:boolean;promotionsEnabled?:boolean;promotionTitle?:string;promotionText?:string;referralBonus?:number;whatsapp?:string;instagram?:string;website?:string;mapUrl?:string};
type PublicPortal={companyId:string;company:string;slug:string;logoUrl:string;phone:string;address:string;welcomeBonus:number;portal:PortalConfig};
function BrandMark({name,logo}:{name:string;logo?:string}){return <div className="guest-brand">{logo?<Image src={logo} alt={`Логотип ${name}`} width={38} height={38} unoptimized/>:<span>{name.slice(0,1).toUpperCase()}</span>}<strong>{name}</strong></div>}
const guestFetch=(url:string,init?:RequestInit)=>fetch(url,{...init,credentials:"include",headers:{...csrfHeaders("guest"),...init?.headers}});

export function JoinPortal({token}:{token:string}){
 const router=useRouter();const[data,setData]=useState<PublicPortal|null>(null),[stage,setStage]=useState<"intro"|"form"|"success">("intro"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[bonus,setBonus]=useState(0);
 useEffect(()=>{fetch(`${base}/public/guest/${token}`).then(r=>r.json()).then(async x=>{if(!x.success)throw new Error(x.error.message);setData(x.data);const me=await guestFetch(`${base}/customer/me`);if(me.ok){const current=await me.json();if(current.data?.companySlug===x.data.slug)router.replace("/customer")}}).catch(e=>setMsg(e.message))},[router,token]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const form=Object.fromEntries(new FormData(e.currentTarget));const referralCode=sessionStorage.getItem("tappix_referral")||"";try{const result=await guestFetch(`${base}/customer/register`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,token,referralCode,consent:form.consent==="on"})}).then(r=>r.json());if(!result.success)throw new Error(result.error.message);sessionStorage.removeItem("tappix_referral");setBonus(result.data.points);setStage("success");setTimeout(()=>router.push("/customer"),1800)}catch(e){setMsg(e instanceof Error?e.message:"Не удалось зарегистрироваться")}finally{setBusy(false)}}
 if(!data)return <div className="guest-loading"><span className="guest-spinner"/>{msg||"Открываем бонусную карту…"}</div>;
 const color=data.portal.primaryColor||"#5B4AE8";const style={"--guest-primary":color,"--guest-hero":data.portal.backgroundUrl?`linear-gradient(180deg,rgba(14,18,30,.18),rgba(14,18,30,.72)),url(${data.portal.backgroundUrl})`:undefined} as React.CSSProperties;
 if(stage==="success")return <main className="guest-success" style={style}><div className="guest-confetti" aria-hidden="true"><i/><i/><i/><i/><i/></div><span className="success-ring"><Check/></span><p>Вы в программе</p><h1>Добро пожаловать!</h1>{bonus>0&&<div><Sparkles/><strong>+{bonus} бонусов</strong><small>уже на вашей карте</small></div>}<p>Открываем личный кабинет…</p></main>;
 return <main className="guest-onboarding" style={style}><section className="guest-hero"><BrandMark name={data.company} logo={data.portal.logoUrl||data.logoUrl}/><div><span className="guest-kicker"><Sparkles/>Бонусная карта бесплатно</span><h1>{data.portal.welcomeTitle||`Добро пожаловать в ${data.company}!`}</h1><p>{data.portal.welcomeText||"Копите бонусы за каждое посещение и получайте персональные предложения."}</p></div></section>{stage==="intro"?<section className="guest-intro-sheet"><div className="benefit-list"><div><WalletCards/><span><strong>Карта всегда с вами</strong><small>Баланс и история в телефоне</small></span></div><div><Gift/><span><strong>Бонусы за посещения</strong><small>{data.welcomeBonus>0?`Стартовый бонус +${data.welcomeBonus}`:"Начисляются автоматически"}</small></span></div><div><Star/><span><strong>Персональные предложения</strong><small>Награды и акции от {data.company}</small></span></div></div><button className="guest-primary" onClick={()=>setStage("form")}>Получить бонусную карту<ChevronRight/></button><small className="guest-trust"><Clock3/>Регистрация займёт меньше минуты</small></section>:<section className="guest-register-sheet"><button className="guest-back" onClick={()=>setStage("intro")}>← Назад</button><header><span>Регистрация</span><h2>Создать карту</h2><p>Заполните основные данные. Вход будет по коду из WhatsApp.</p></header>{msg&&<div className="guest-error" role="alert">{msg}</div>}<form onSubmit={submit}><div className="guest-fields"><label>Имя<input name="firstName" autoComplete="given-name" required/></label><label>Фамилия<input name="lastName" autoComplete="family-name" required/></label></div><label>Телефон<input name="phone" type="tel" inputMode="tel" autoComplete="tel" placeholder="+7 700 000 00 00" required/></label><label>Дата рождения<input name="birthday" type="date" required/></label>{data.portal.showGender!==false&&<fieldset><legend>Пол</legend><div className="guest-segments"><label><input type="radio" name="gender" value="female"/><span>Женский</span></label><label><input type="radio" name="gender" value="male"/><span>Мужской</span></label><label><input type="radio" name="gender" value="other"/><span>Не указывать</span></label></div></fieldset>}{data.portal.requireEmail&&<label>Email<input name="email" type="email" autoComplete="email" required/></label>}{data.portal.requireCity&&<label>Город<input name="city" autoComplete="address-level2" required/></label>}<label className="guest-consent"><input name="consent" type="checkbox" required/><span>Принимаю условия программы и согласен(на) на обработку данных.</span></label><button className="guest-primary" disabled={busy}>{busy?"Создаём карту…":"Создать карту"}</button></form></section>}<footer>Работает на <strong>Tappix</strong></footer></main>
}
