"use client";
import { FormEvent, useEffect, useState } from "react";
import { CalendarDays, Check, Code2, Copy, ExternalLink, FileImage, Globe2, KeyRound, Plus, Trash2, Upload } from "lucide-react";
import { api, assetUrl } from "@/lib/api";
import { SectionShell } from "./section-shell";
import { useConfirm } from "./use-confirm";

type Website={headline:string;description:string;services:string[];phone:string;address:string;published:boolean};
type Workspace={id:string;name:string;slug:string;current:boolean};
export function WebsitePage(){const[value,setValue]=useState<Website>({headline:"",description:"",services:[],phone:"",address:"",published:false});const[msg,setMsg]=useState("");const[slug,setSlug]=useState("");useEffect(()=>{api<Website>("/website").then(site=>setValue({...site,services:site.services??[]})).catch(e=>setMsg(e.message));api<Workspace[]>("/workspaces").then(spaces=>{const current=spaces.find(x=>x.current)||spaces[0];if(current)setSlug(current.slug)}).catch(()=>undefined)},[]);const siteUrl=slug?`/site/${slug}`:"";async function save(e:FormEvent){e.preventDefault();try{await api("/website",{method:"PATCH",body:JSON.stringify(value)});setMsg("Мини-сайт сохранён")}catch(e){setMsg(e instanceof Error?e.message:"Ошибка")}}return <SectionShell active="/website" title="Мини-сайт" subtitle="Публичная страница компании"><div className="extension-head">{msg&&<span><Check/>{msg}</span>}{siteUrl&&<a href={siteUrl} target="_blank" rel="noopener noreferrer"><ExternalLink/>Открыть сайт</a>}</div><form className="settings-card" onSubmit={save}><div className="settings-title"><span><Globe2/></span><div><h2>Содержимое страницы</h2><p>{siteUrl?`Изменения публикуются по адресу ${siteUrl}.`:"Изменения публикуются на публичной странице компании."}</p></div></div><div className="form-grid"><label>Заголовок<input value={value.headline} onChange={e=>setValue({...value,headline:e.target.value})}/></label><label>Телефон<input value={value.phone} onChange={e=>setValue({...value,phone:e.target.value})}/></label><label>Адрес<input value={value.address} onChange={e=>setValue({...value,address:e.target.value})}/></label><label>Услуги через запятую<input value={value.services.join(", ")} onChange={e=>setValue({...value,services:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label></div><label>Описание<textarea rows={5} value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></label><label className="toggle-row"><input type="checkbox" checked={value.published} onChange={e=>setValue({...value,published:e.target.checked})}/>Сайт опубликован</label><button className="primary-action">Сохранить</button></form></SectionShell>}

type Booking={id:string;customerName:string;phone:string;service:string;startsAt:string;status:string;branch:string};
export function BookingsPage(){const[items,setItems]=useState<Booking[]>([]),[msg,setMsg]=useState("");const load=()=>api<Booking[]>("/bookings").then(setItems).catch(e=>setMsg(e.message));useEffect(()=>{void load()},[]);async function status(id:string,value:string){try{await api(`/bookings/${id}`,{method:"PATCH",body:JSON.stringify({status:value})});setMsg("Статус записи обновлён");await load()}catch(e){setMsg(e instanceof Error?e.message:"Ошибка")}}return <SectionShell active="/bookings" title="Онлайн-запись" subtitle="Заявки с публичного сайта">{msg&&<div className="portal-message">{msg}</div>}<div className="data-card"><table><thead><tr><th>Клиент</th><th>Услуга</th><th>Филиал</th><th>Дата</th><th>Статус</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.customerName}</strong><br/>{x.phone}</td><td>{x.service}</td><td>{x.branch}</td><td>{new Date(x.startsAt).toLocaleString("ru-RU")}</td><td><select value={x.status} onChange={e=>void status(x.id,e.target.value)}><option value="new">Новая</option><option value="confirmed">Подтверждена</option><option value="completed">Завершена</option><option value="cancelled">Отменена</option></select></td></tr>)}</tbody></table>{!items.length&&<div className="zero"><CalendarDays/><strong>Записей пока нет</strong></div>}</div></SectionShell>}

type APIKey={id:string;name:string;prefix:string;active:boolean;createdAt:string;lastUsedAt?:string};
export function APIKeysPage(){const{ask,dialog}=useConfirm();const[items,setItems]=useState<APIKey[]>([]),[open,setOpen]=useState(false),[secret,setSecret]=useState(""),[msg,setMsg]=useState("");const load=()=>api<APIKey[]>("/api-keys").then(setItems).catch(e=>setMsg(e.message));useEffect(()=>{void load()},[]);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();try{const result=await api<{key:string}>("/api-keys",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setSecret(result.key);setOpen(false);await load()}catch(e){setMsg(e instanceof Error?e.message:"Ошибка")}}async function revoke(id:string){if(!await ask({ title: "Отозвать API-ключ?", description: "Интеграции, использующие этот ключ, перестанут работать.", confirmLabel: "Отозвать" }))return;await api(`/api-keys/${id}`,{method:"DELETE"});setMsg("Ключ отозван");await load()}return <SectionShell active="/api-keys" title="API-ключи" subtitle="Безопасный доступ внешних CRM"><div className="toolbar"><span>{msg}</span><button className="primary-action" onClick={()=>setOpen(true)}><Plus/>Создать ключ</button></div>{secret&&<div className="secret-callout"><KeyRound/><div><strong>Скопируйте ключ сейчас</strong><code>{secret}</code></div><button onClick={()=>navigator.clipboard.writeText(secret)}><Copy/>Копировать</button></div>}<div className="card-grid">{items.map(x=><article className="entity-card" key={x.id}><span className="entity-icon"><Code2/></span><div><h2>{x.name}</h2><p><code>{x.prefix}••••••••</code></p><span className={x.active?"status":"mail-failed"}>{x.active?"Активен":"Отозван"}</span></div>{x.active&&<button className="danger-icon" onClick={()=>void revoke(x.id)}><Trash2/></button>}</article>)}</div>{open&&<div className="sheet-bg"><form className="sheet" onSubmit={create}><h2>Новый API-ключ</h2><label>Название<input name="name" required placeholder="Kaspi CRM"/></label><label>Истекает<input name="expiresAt" type="date"/></label><div><button type="button" onClick={()=>setOpen(false)}>Отмена</button><button className="primary-action">Создать</button></div></form></div>}{dialog}</SectionShell>}

type Asset={id:string;name:string;kind:string;contentType:string;size:number;url:string;createdAt:string};
export function FilesPage(){const{ask,dialog}=useConfirm();const[items,setItems]=useState<Asset[]>([]),[msg,setMsg]=useState("");const load=()=>api<Asset[]>("/files").then(setItems).catch(e=>setMsg(e.message));useEffect(()=>{void load()},[]);const href=assetUrl;async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{await api("/upload",{method:"POST",body:form});setMsg("Файл загружен");e.currentTarget.reset();await load()}catch(e){setMsg(e instanceof Error?e.message:"Ошибка")}}async function remove(id:string){if(!await ask({ title: "Удалить файл?", description: "Ссылки на него перестанут открываться.", confirmLabel: "Удалить" }))return;await api(`/files/${id}`,{method:"DELETE"});await load()}return <SectionShell active="/files" title="Файлы" subtitle="Логотипы, изображения и документы"><div className="file-layout"><form className="upload-card" onSubmit={upload}><Upload/><h2>Загрузить файл</h2><p>JPG, PNG, WebP или PDF до 10 МБ.</p><label>Файл<input name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></label><label>Тип файла<select name="kind"><option value="logo">Логотип</option><option value="asset">Изображение</option><option value="document">Документ</option></select></label><button className="primary-action">Загрузить</button><small>{msg}</small></form><div className="card-grid">{items.map(x=><article className="entity-card" key={x.id}><span className="entity-icon"><FileImage/></span><div><h2>{x.name}</h2><p>{x.kind} · {(x.size/1024).toFixed(1)} КБ</p><a href={href(x.url)} target="_blank" rel="noopener noreferrer">Открыть</a></div><button className="danger-icon" onClick={()=>remove(x.id)}><Trash2/></button></article>)}</div></div>{dialog}</SectionShell>}

export { IntegrationsPage } from "./integration-hub-page";
