"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, Check, Gift, Menu, QrCode, Send, Users, X } from "lucide-react";
import { API_URL } from "@/lib/api";
import { fallbackPlans, planPresentation, type PlanDefinition } from "@/lib/plans";

export function MarketingHome() {
  const [annual, setAnnual] = useState(false);
  const [plans, setPlans] = useState<PlanDefinition[]>(fallbackPlans);
  const [menu, setMenu] = useState(false);
  useEffect(() => { fetch(`${API_URL}/public/plans`).then(r => r.json()).then(r => r.success && setPlans(r.data)).catch(() => {}); }, []);
  return <div className="marketing-home">
    <header className="marketing-nav"><Link className="marketing-brand" href="/welcome"><Image src="/tappix-mark.png" alt="" aria-hidden width={30} height={30}/><strong>Tappix</strong></Link><nav className={menu ? "open" : ""} aria-label="Навигация сайта"><a href="#product">Возможности</a><a href="#how">Как работает</a><a href="#pricing">Тарифы</a><Link href="/login">Войти</Link><Link className="marketing-nav-cta" href="/login">7 дней бесплатно</Link></nav><button className="marketing-menu" aria-label={menu ? "Закрыть меню" : "Открыть меню"} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></header>
    <main>
      <section className="marketing-hero"><div><span className="marketing-kicker">CRM + ПРОГРАММА ЛОЯЛЬНОСТИ</span><h1>Возвращайте клиентов чаще</h1><p>Tappix объединяет клиентскую базу, программу лояльности, аналитику и автоматизацию в одной понятной системе.</p><div className="marketing-actions"><Link className="marketing-primary" href="/login">Попробовать бесплатно <ArrowRight/></Link><a className="marketing-secondary" href="#product">Посмотреть возможности</a></div><small>7 дней бесплатно · без сложной настройки</small></div><DashboardPreview/></section>
      <section className="marketing-flow" id="how"><header><span>КАК ЭТО РАБОТАЕТ</span><h2>Один понятный путь к повторной покупке</h2></header><div>{[[QrCode,"Регистрация","Клиент открывает QR или NFC"],[Users,"Цифровая карта","Получает карту без приложения"],[Gift,"Прогресс","Копит штампы или бонусы"],[ArrowRight,"Возвращение","Приходит снова за наградой"]].map(([Icon,title,text],i)=><article key={String(title)}><b>{i+1}</b><Icon/><strong>{title as string}</strong><p>{text as string}</p></article>)}</div></section>
      <section className="marketing-showcase" id="product"><header><span>ОДИН TAPPIX</span><h2>Всё необходимое для работы с клиентами</h2><p>От регистрации гостя до решения владельца — данные остаются в одном продукте.</p></header><div className="showcase-grid"><ProductBlock icon={<Users/>} label="CRM И КЛИЕНТЫ" title="Видно, кто возвращается" text="Поиск, сегменты, прогресс, история визитов и наград в одном профиле." variant="customers"/><ProductBlock icon={<Gift/>} label="ЛОЯЛЬНОСТЬ" title="Программа, понятная клиенту" text="Штампы, бонусы и награды с живым preview клиентской карты." variant="loyalty"/><ProductBlock icon={<BarChart3/>} label="АНАЛИТИКА" title="Ответы, а не шум" text="Повторные визиты, удержание и действия на основе реальных данных." variant="analytics"/><ProductBlock icon={<Send/>} label="КАМПАНИИ" title="Вернуть клиента проще" text="Готовые сценарии для дня рождения, спящих клиентов и близких к награде." variant="campaigns"/></div></section>
      <section className="marketing-pricing" id="pricing"><header><span>ПРОСТЫЕ ТАРИФЫ</span><h2>Начните с одной точки. Растите без переезда.</h2><div className="billing-switch" role="group" aria-label="Период оплаты"><button className={!annual ? "active" : ""} onClick={() => setAnnual(false)}>Ежемесячно</button><button className={annual ? "active" : ""} onClick={() => setAnnual(true)}>За год <small>2 месяца бесплатно</small></button></div></header><div className="marketing-plans">{plans.map(plan => {const info=planPresentation[plan.id]; return <article className={plan.highlighted ? "featured" : ""} key={plan.id}>{plan.highlighted&&<b className="plan-popular">Популярный</b>}<h3>{plan.name}</h3><p>{plan.description}</p><strong>{(annual ? plan.annualPrice : plan.monthlyPrice).toLocaleString("ru-RU")} ₸</strong><small>/{annual ? "год" : "месяц"} · {info.locations}</small><ul>{info.features.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul><Link href="/login">{plan.id === "growth" ? "Попробовать Pro" : plan.id === "pro" ? "Выбрать Business" : "Начать бесплатно"}</Link></article>})}</div><p className="pricing-note">Нужны индивидуальные лимиты, SLA или custom-интеграции? <a href="mailto:hello@tappix.kz">Обсудить Enterprise</a></p></section>
      <section className="marketing-final"><span>ГОТОВЫ К ПЕРВОМУ ВОЗВРАТУ?</span><h2>Запустите программу лояльности за несколько шагов</h2><p>Бизнес → филиал → механика → награда → preview → запуск.</p><Link href="/login">Начать бесплатно <ArrowRight/></Link></section>
    </main><footer><div className="marketing-brand"><Image src="/tappix-mark.png" alt="" aria-hidden width={26} height={26}/><strong>Tappix</strong></div><p>CRM и программа лояльности для бизнеса.</p><Link href="/login">Войти</Link></footer>
  </div>;
}

function DashboardPreview(){return <div className="marketing-dashboard" aria-label="Представление интерфейса Tappix"><aside><div><i/>Tappix</div>{["Обзор","Клиенты","Программа","Кампании","Аналитика"].map((x,i)=><span className={i===0?"active":""} key={x}><i/>{x}</span>)}</aside><section><header><div><small>СЕГОДНЯ</small><strong>Программа работает</strong></div><button>Staff Mode</button></header><div className="preview-metrics">{[["КЛИЕНТЫ","2 481"],["ВИЗИТЫ","186"],["ВОЗВРАЩАЮТСЯ","42%"]].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong><span>↑ за период</span></article>)}</div><div className="preview-chart"><header><strong>Активность клиентов</strong><small>Последние 7 дней</small></header><div>{[42,58,49,71,62,84,76].map((x,i)=><i style={{height:`${x}%`}} key={i}/>)}</div></div></section></div>}
function ProductBlock({icon,label,title,text,variant}:{icon:React.ReactNode;label:string;title:string;text:string;variant:string}){return <article className={`showcase-block ${variant}`}><div><span>{icon}{label}</span><h3>{title}</h3><p>{text}</p></div><div className="showcase-visual">{variant==="customers"?<>{["Мадина К.","Алексей П.","Диана С."].map((x,i)=><span key={x}><i>{x[0]}</i><b>{x}<small>{["Лояльный клиент","Близко к награде","Новый клиент"][i]}</small></b><em>{["12 визитов","4 / 5","1 визит"][i]}</em></span>)}</>:variant==="loyalty"?<div className="mini-wallet"><small>ВАША КАРТА</small><strong>4 из 5 посещений</strong><div>{[1,2,3,4,5].map(x=><i className={x<5?"done":""} key={x}>{x<5?<Check/>:null}</i>)}</div><p>Ещё одно посещение — и подарок ваш</p><button>Показать QR</button></div>:variant==="analytics"?<div className="mini-analytics">{[62,78,54,88,72,94,84].map((x,i)=><i style={{height:`${x}%`}} key={i}/>)}</div>:<div className="mini-campaign"><span><Check/>Аудитория<strong>184 клиента</strong></span><span><Check/>Сообщение<strong>Готово</strong></span><span><i/>Отправка<strong>Сегодня, 18:00</strong></span></div>}</div></article>}
