"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, Check, Copy, ExternalLink, Eye, EyeOff, MapPin, MoreHorizontal, Nfc, Pencil, Plus, QrCode, Radio, ScanLine, Trash2, X } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { api } from "@/lib/api";
import { SectionShell } from "./section-shell";

type Branch={id:string;name:string;address:string;active:boolean};
type Device={id:string;branchId:string;branch:string;kind:"nfc"|"qr";name:string;token:string;url:string;destination:string;active:boolean;scans:number;lastScannedAt?:string};
const destinations:Record<string,string>={join:"Регистрация клиента",reviews:"Сбор отзывов",website:"Мини-сайт",booking:"Онлайн-запись"};

export function NFCQRManager(){
 const[items,setItems]=useState<Device[]>([]),[branches,setBranches]=useState<Branch[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Device|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[copied,setCopied]=useState(""),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{const[d,b]=await Promise.all([api<Device[]>("/devices"),api<Branch[]>("/branches")]);setItems(d);setBranches(b)}catch(e){setMessage(e instanceof Error?e.message:"Не удалось загрузить NFC и QR")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const stats=useMemo(()=>({active:items.filter(x=>x.active).length,scans:items.reduce((n,x)=>n+x.scans,0),last:items.filter(x=>x.lastScannedAt).sort((a,b)=>String(b.lastScannedAt).localeCompare(String(a.lastScannedAt)))[0]}),[items]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const body=Object.fromEntries(new FormData(e.currentTarget));try{if(editing)await api(`/devices/${editing.id}`,{method:"PATCH",body:JSON.stringify({...body,active:editing.active})});else await api("/devices",{method:"POST",body:JSON.stringify(body)});setMessage(editing?"Точка обновлена":"Новая точка готова к использованию");setOpen(false);setEditing(null);await load()}catch(e){setMessage(e instanceof Error?e.message:"Не удалось сохранить точку")}finally{setSaving(false)}}
 async function toggle(item:Device){try{await api(`/devices/${item.id}`,{method:"PATCH",body:JSON.stringify({branchId:item.branchId,kind:item.kind,name:item.name,destination:item.destination,active:!item.active})});setMessage(item.active?"Точка приостановлена":"Точка снова активна");await load()}catch(e){setMessage(e instanceof Error?e.message:"Не удалось изменить статус")}}
 async function remove(item:Device){if(!confirm(`Удалить точку «${item.name}»? Напечатанный QR и записанная NFC-метка перестанут работать.`))return;try{await api(`/devices/${item.id}`,{method:"DELETE"});setMessage("Точка удалена");await load()}catch(e){setMessage(e instanceof Error?e.message:"Не удалось удалить точку")}}
 async function copy(item:Device){await navigator.clipboard.writeText(item.url);setCopied(item.id);setMessage("Ссылка скопирована");setTimeout(()=>setCopied(""),1800)}
 function edit(item:Device){setEditing(item);setOpen(true)}
 return <SectionShell active="/devices" title="NFC и QR" subtitle="Точки входа в программу лояльности">
  {message&&<div className="nfc-notice" role="status"><Check/>{message}</div>}
  <div className="nfc-flow"><span><QrCode/></span><div><strong>Гость сканирует → получает карту → вы отмечаете визит</strong><small>Ссылка постоянная: дизайн и механику можно менять без перепечатки QR.</small></div><Link href="/scanner"><ScanLine/>Открыть сканер</Link></div>
  <section className="nfc-overview"><div><span className="nfc-kicker"><Radio/>SMART LINKS</span><h2>Каждое касание превращается в клиента</h2><p>Создавайте NFC и QR-точки, отслеживайте сканирования и направляйте гостей в нужный сценарий.</p></div><button onClick={()=>{setEditing(null);setOpen(true)}}><Plus/>Новая точка</button></section>
  <div className="nfc-stats"><article><span><Activity/></span><div><small>Активные точки</small><strong>{stats.active}<i> / {items.length}</i></strong></div></article><article><span><ScanLine/></span><div><small>Всего сканирований</small><strong>{stats.scans.toLocaleString("ru-RU")}</strong></div></article><article><span><Radio/></span><div><small>Последняя активность</small><strong>{stats.last?.lastScannedAt?new Date(stats.last.lastScannedAt).toLocaleDateString("ru-RU",{day:"numeric",month:"short"}):"Пока нет"}</strong></div></article></div>
  {loading?<div className="nfc-loading"><ScanLine/><p>Загружаем точки…</p></div>:items.length===0?<div className="nfc-empty"><QrCode/><h2>Создайте первую точку</h2><p>Разместите QR на стойке или запишите ссылку на NFC-метку.</p><button onClick={()=>setOpen(true)}><Plus/>Создать точку</button></div>:<div className="nfc-grid">{items.map(item=><article className={`nfc-card ${item.active?"":"disabled"}`} key={item.id}><header><span className="nfc-kind">{item.kind==="nfc"?<Nfc/>:<QrCode/>}</span><div><small>{item.kind.toUpperCase()} · {item.branch}</small><h2>{item.name}</h2></div><button className="nfc-more" aria-label="Редактировать" onClick={()=>edit(item)}><MoreHorizontal/></button></header><div className="nfc-visual"><div className="nfc-qr"><QRCodeSVG value={item.url} size={132} level="M" marginSize={1}/></div><div className="nfc-card-stats"><span><small>Сканирования</small><strong>{item.scans}</strong></span><span><small>Последнее</small><strong>{item.lastScannedAt?new Date(item.lastScannedAt).toLocaleDateString("ru-RU",{day:"numeric",month:"short"}):"—"}</strong></span><span><small>Сценарий</small><b>{destinations[item.destination]||item.destination}</b></span></div></div><div className="nfc-status"><span className={item.active?"active":"paused"}><i/>{item.active?"Активна":"Приостановлена"}</span><span><MapPin/>{item.branch}</span></div><div className="nfc-link"><code>{item.url}</code><button onClick={()=>copy(item)} aria-label="Скопировать ссылку">{copied===item.id?<Check/>:<Copy/>}</button><a href={item.url} target="_blank" rel="noreferrer" aria-label="Открыть ссылку"><ExternalLink/></a></div><footer><button onClick={()=>edit(item)}><Pencil/>Настроить</button><button onClick={()=>toggle(item)}>{item.active?<><EyeOff/>Отключить</>:<><Eye/>Включить</>}</button><button className="danger" onClick={()=>remove(item)} aria-label="Удалить"><Trash2/></button></footer></article>)}</div>}
  {open&&<div className="nfc-modal-bg" onMouseDown={e=>{if(e.target===e.currentTarget){setOpen(false);setEditing(null)}}}><form className="nfc-modal" onSubmit={submit}><header><div><small>{editing?"НАСТРОЙКА ТОЧКИ":"НОВАЯ ТОЧКА"}</small><h2>{editing?editing.name:"Создать NFC или QR"}</h2><p>Ссылка начнёт работать сразу после создания.</p></div><button type="button" onClick={()=>{setOpen(false);setEditing(null)}} aria-label="Закрыть"><X/></button></header><div className="nfc-form"><fieldset><legend>Тип точки</legend><div className="nfc-kind-select"><label><input type="radio" name="kind" value="qr" defaultChecked={!editing||editing.kind==="qr"}/><span><QrCode/><strong>QR-код</strong><small>Для печати и экранов</small></span></label><label><input type="radio" name="kind" value="nfc" defaultChecked={editing?.kind==="nfc"}/><span><Nfc/><strong>NFC-метка</strong><small>Для касания телефоном</small></span></label></div></fieldset><label>Название<input name="name" defaultValue={editing?.name||""} placeholder="Стойка регистрации" required autoFocus/></label><div className="nfc-form-row"><label>Филиал<select name="branchId" defaultValue={editing?.branchId} required>{branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>Куда вести гостя<select name="destination" defaultValue={editing?.destination||"join"}>{Object.entries(destinations).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div><div className="nfc-hint"><Radio/><p><strong>Одна постоянная ссылка</strong><span>Вы сможете менять сценарий позже, не перепечатывая QR и не перезаписывая NFC.</span></p></div></div><footer><button type="button" onClick={()=>{setOpen(false);setEditing(null)}}>Отмена</button><button className="primary" disabled={saving}>{saving?"Сохраняем…":editing?"Сохранить":"Создать точку"}</button></footer></form></div>}
 </SectionShell>
}
