"use client";
import { useEffect, useState } from "react";
import { Check, Coins, Eye, Gift, Minus, Percent, Plus, QrCode, Save, Stamp, X } from "lucide-react";
import { api } from "@/lib/api";
import { useDialogFocusTrap } from "./use-dialog-focus-trap";

type Mode="points"|"stamps"|"discount";
type Settings={loyaltyMode:Mode;stampsTarget:number;stampReward:string;discountStart:number;discountStep:number;discountMax:number;visitsPerStep:number;primaryColor?:string;[key:string]:unknown};
const defaults:Settings={loyaltyMode:"points",stampsTarget:6,stampReward:"Подарок",discountStart:3,discountStep:2,discountMax:15,visitsPerStep:3};
const modes=[
  {id:"stamps" as const,Icon:Stamp,title:"Подарок за посещения",help:"Клиент приходит несколько раз и получает подарок",best:"кафе, стоматологии и салоны",technical:"Штамп-карта"},
  {id:"points" as const,Icon:Coins,title:"Бонусы с покупок",help:"Часть каждой покупки возвращается клиенту бонусами",best:"магазины и средний чек",technical:"Бонусная программа"},
  {id:"discount" as const,Icon:Percent,title:"Скидка растёт с клиентом",help:"Чем чаще клиент возвращается, тем выше его скидка",best:"retail и салоны",technical:"Накопительная скидка"},
];
export function ProgramMechanics(){
  const [value,setValue]=useState<Settings>(defaults),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[previewOpen,setPreviewOpen]=useState(false),[publishOpen,setPublishOpen]=useState(false),[dirty,setDirty]=useState(false);
  const previewDialog=useDialogFocusTrap<HTMLElement>(previewOpen,()=>setPreviewOpen(false));
  const publishDialog=useDialogFocusTrap<HTMLElement>(publishOpen,()=>setPublishOpen(false));
  useEffect(()=>{api<Partial<Settings>>( "/settings/guest-portal").then(x=>setValue({...defaults,...x})).catch(e=>setMessage(e.message))},[]);
  function update(patch:Partial<Settings>){setValue(current=>({...current,...patch}));setDirty(true);setMessage("")}
  async function save(){setSaving(true);setMessage("");try{await api("/settings/guest-portal",{method:"PATCH",body:JSON.stringify(value)});setMessage("Программа обновлена");setDirty(false);setPublishOpen(false)}catch(e){setMessage(e instanceof Error?e.message:"Не удалось опубликовать программу")}finally{setSaving(false)}}
  const accent=value.primaryColor||"#6352ee";
  const card=<div className="phone-preview"><div className="phone-top"><i/><i/><i/></div><div className="mini-pass" style={{"--pass-accent":accent} as React.CSSProperties}><header><span>D</span><strong>Dentline</strong><i>{value.loyaltyMode==="stamps"?"ПОСЕЩЕНИЯ":value.loyaltyMode==="discount"?"СКИДКА":"БОНУСЫ"}</i></header>{value.loyaltyMode==="points"&&<div className="mini-balance"><small>ВАШ БАЛАНС</small><strong>420</strong><span>≈ 420 ₸ на следующую покупку</span></div>}{value.loyaltyMode==="stamps"&&<><div className="mini-stamps">{Array.from({length:Math.min(12,value.stampsTarget)},(_,i)=><span className={i<1?"filled":""} key={i}>{i<1?<Check/>:i+1}</span>)}</div><p className="mini-reward"><Gift/>Ещё {Math.max(value.stampsTarget-1,0)} посещений: {value.stampReward||"Ваша награда"}</p></>}{value.loyaltyMode==="discount"&&<div className="mini-discount"><small>ВАША СКИДКА</small><strong>{value.discountStart}%</strong><p>Следующий уровень после {value.visitsPerStep} визитов</p></div>}<footer><div><small>УЧАСТНИК</small><strong>Мадина</strong></div><b><QrCode/></b></footer></div></div>;
  return <section className="mechanics-studio">
    <header><div><small>НАСТРОЙКА ПРОГРАММЫ</small><h2>За что клиент будет возвращаться?</h2><p>Выберите понятный сценарий, настройте награду и проверьте результат глазами клиента.</p></div>{message&&<span><Check/>{message}</span>}</header>
    <div className="mechanics-config">
      <fieldset className="mechanics-choice"><legend><b>1</b><span>Как клиент получает прогресс<small>Выберите один основной сценарий</small></span></legend><div className="mechanics-modes">{modes.map(({id,Icon,title,help,best,technical})=><button type="button" aria-pressed={value.loyaltyMode===id} className={value.loyaltyMode===id?"active":""} onClick={()=>update({loyaltyMode:id})} key={id}><span><Icon/></span><div><strong>{title}</strong><p>{help}</p><small>{technical} · {best}</small></div>{value.loyaltyMode===id&&<Check/>}</button>)}</div></fieldset>
      <div className="mechanics-fields">
        {value.loyaltyMode==="points"&&<div className="mechanics-explain"><Coins/><div><strong>Клиент копит бонусы после покупок</strong><p>Размер начислений задаётся ниже в дополнительных правилах. Баланс и его денежная ценность видны в карте.</p></div></div>}
        {value.loyaltyMode==="stamps"&&<><div className="visit-goal"><div><b>2</b><span><strong>Через сколько посещений выдать награду?</strong><small>Чаще всего хорошо работают 5–8 посещений.</small></span></div><div className="visit-stepper"><button type="button" aria-label="Уменьшить количество посещений" onClick={()=>update({stampsTarget:Math.max(2,value.stampsTarget-1)})}><Minus/></button><strong>{value.stampsTarget}<small>посещений</small></strong><button type="button" aria-label="Увеличить количество посещений" onClick={()=>update({stampsTarget:Math.min(30,value.stampsTarget+1)})}><Plus/></button></div></div><div className="reward-name-field"><div><b>3</b><span><strong>Что получит клиент?</strong><small>Название должно быть понятно без дополнительных объяснений.</small></span></div><label>Название награды<input value={value.stampReward} onChange={e=>update({stampReward:e.target.value})} placeholder="Например: Бесплатная чистка зубов"/></label></div></>}
        {value.loyaltyMode==="discount"&&<div className="discount-field-grid"><label>Начальная скидка, %<input type="number" min="0" max="50" value={value.discountStart} onChange={e=>update({discountStart:Number(e.target.value)})}/></label><label>Повышать на, %<input type="number" min="1" max="20" value={value.discountStep} onChange={e=>update({discountStep:Number(e.target.value)})}/></label><label>После посещений<input type="number" min="1" max="50" value={value.visitsPerStep} onChange={e=>update({visitsPerStep:Number(e.target.value)})}/></label><label>Максимальная скидка, %<input type="number" min="1" max="70" value={value.discountMax} onChange={e=>update({discountMax:Number(e.target.value)})}/></label></div>}
      </div>
      <div className="mechanics-action"><button type="button" className="mechanics-preview-button" onClick={()=>setPreviewOpen(true)}><Eye/>Посмотреть глазами клиента</button><span>{dirty?"Есть неопубликованные изменения":"Все изменения опубликованы"}</span><button className="mechanics-save" disabled={saving||!dirty} onClick={()=>setPublishOpen(true)}><Save/>Опубликовать</button></div>
    </div>
    {previewOpen&&<div className="program-dialog-bg" onMouseDown={e=>{if(e.target===e.currentTarget)setPreviewOpen(false)}}><section ref={previewDialog} className="program-preview-dialog" role="dialog" aria-modal="true" aria-labelledby="program-preview-title"><header><div><small>ПРЕДПРОСМОТР</small><h2 id="program-preview-title">Глазами клиента</h2></div><button type="button" onClick={()=>setPreviewOpen(false)} aria-label="Закрыть"><X/></button></header>{card}<p><Check/>Демонстрация: реальный баланс и имя будут индивидуальными.</p></section></div>}
    {publishOpen&&<div className="program-dialog-bg" onMouseDown={e=>{if(e.target===e.currentTarget)setPublishOpen(false)}}><section ref={publishDialog} className="program-publish-dialog" role="dialog" aria-modal="true" aria-labelledby="program-publish-title"><header><div><small>ПРОВЕРЬТЕ ПЕРЕД ЗАПУСКОМ</small><h2 id="program-publish-title">Вы запускаете программу</h2></div><button type="button" onClick={()=>setPublishOpen(false)} aria-label="Закрыть"><X/></button></header><dl><div><dt>Тип программы</dt><dd>{modes.find(x=>x.id===value.loyaltyMode)?.title}</dd></div>{value.loyaltyMode==="stamps"&&<><div><dt>После</dt><dd>{value.stampsTarget} посещений</dd></div><div><dt>Клиент получает</dt><dd>{value.stampReward||"Награда не указана"}</dd></div><div><dt>После награды</dt><dd>Карта начинается заново</dd></div></>}</dl><footer><button type="button" onClick={()=>setPublishOpen(false)}>Вернуться к настройке</button><button type="button" className="primary" disabled={saving||value.loyaltyMode==="stamps"&&!value.stampReward.trim()} onClick={()=>void save()}>{saving?"Запускаем…":"Запустить программу"}</button></footer></section></div>}
  </section>
}
