"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowDown, Check, CheckCircle2, ChevronDown, Copy, Gift, Link2, LoaderCircle, Pause, Play, QrCode, ShieldCheck, ShoppingBag, Trophy, UserRound, X } from "lucide-react";
import { api } from "@/lib/api";
import { SectionShell } from "./section-shell";
import { EmptyState, ErrorState, InfoCallout, Skeleton, StatusBadge } from "./ui-system";

type Program={id:string;name:string;status:"draft"|"active"|"paused";referrerRewardValue:number;friendRewardValue:number;minimumPurchaseAmount:number;rewardDelayDays:number;maxRewardsPerCustomer:number|null;maxRewardsPerMonth:number|null;updatedAt?:string};
type Analytics={clicks:number;registrations:number;qualified:number;rewarded:number;revenue:number;rewardCost:number;conversionRate:number;qualificationRate:number;leaders:{customerId:string;name:string;referralCode:string;invited:number;rewarded:number;revenue:number}[]};
const initial:Program={id:"",name:"Пригласи друга",status:"draft",referrerRewardValue:300,friendRewardValue:200,minimumPurchaseAmount:3000,rewardDelayDays:3,maxRewardsPerCustomer:10,maxRewardsPerMonth:100};
const emptyStats:Analytics={clicks:0,registrations:0,qualified:0,rewarded:0,revenue:0,rewardCost:0,conversionRate:0,qualificationRate:0,leaders:[]};

export function ReferralsPage(){
 const[program,setProgram]=useState<Program>(initial),[stats,setStats]=useState<Analytics>(emptyStats),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[dirty,setDirty]=useState(false),[exampleOpen,setExampleOpen]=useState(false);
 async function load(){setLoading(true);setError("");try{const[p,a]=await Promise.all([api<Program|null>("/referrals/program"),api<Analytics>("/referrals/analytics")]);if(p)setProgram(p);setStats(a)}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить программу")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function update(patch:Partial<Program>){setProgram(current=>({...current,...patch}));setDirty(true);setMessage("")}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const submitter=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;const status=(submitter?.value||program.status) as Program["status"];try{await api("/referrals/program",{method:"PUT",body:JSON.stringify({...program,status,maxRewardsPerCustomer:program.maxRewardsPerCustomer||0,maxRewardsPerMonth:program.maxRewardsPerMonth||0})});setProgram(value=>({...value,status}));setDirty(false);setMessage(status==="active"?"Реферальная программа запущена":status==="paused"?"Программа приостановлена":"Изменения сохранены");await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить программу")}finally{setSaving(false)}}
 const money=(value:number)=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"KZT",maximumFractionDigits:0}).format(value);
 return <SectionShell active="/referrals" title="Реферальная программа" subtitle="Постоянный клиент делится ссылкой. После первой покупки друга бонус получают оба.">
  {loading?<div className="referral-loading"><Skeleton lines={5}/></div>:error?<ErrorState title="Не удалось загрузить реферальную программу" description={error} retry={()=>void load()}/>:<>
   {message&&<div className="referral-toast" role="status" aria-live="polite"><CheckCircle2/>{message}<button onClick={()=>setMessage("")} aria-label="Закрыть"><X/></button></div>}
   <section className="referral-intro"><div><span>КАК ЭТО РАБОТАЕТ</span><h2>Приглашайте новых клиентов</h2><p>Бонусы начисляются только после подтверждённой покупки — не за простую регистрацию.</p></div><StatusBadge tone={program.status==="active"?"success":program.status==="paused"?"warning":"neutral"}>{program.status==="active"?"Программа активна":program.status==="paused"?"На паузе":"Черновик"}</StatusBadge></section>
   <ReferralFlow referrer={program.referrerRewardValue} friend={program.friendRewardValue}/>
   <div className="referral-editor-grid"><form className="referral-editor" onSubmit={e=>void save(e)}>
    <header><div><h2>Условия программы</h2><p>Настройте базовые условия. Ограничения можно открыть при необходимости.</p></div>{dirty&&<span>Не сохранено</span>}</header>
    <div className="referral-basic-fields"><label><span>Что получает тот, кто приглашает?</span><div className="referral-value-input"><input type="number" min="0" value={program.referrerRewardValue} onChange={e=>update({referrerRewardValue:Number(e.target.value)})}/><b>бонусов</b></div><small>Начислим после первой подтверждённой покупки друга.</small></label><label><span>Что получает новый клиент?</span><div className="referral-value-input"><input type="number" min="0" value={program.friendRewardValue} onChange={e=>update({friendRewardValue:Number(e.target.value)})}/><b>бонусов</b></div><small>Начислим после его первой покупки.</small></label><label><span>Когда приглашение считается успешным?</span><select value="first_paid_purchase" disabled><option value="first_paid_purchase">После первой оплаченной покупки</option></select><small>Другие условия появятся позже.</small></label></div>
    <details className="referral-advanced"><summary><span><ShieldCheck/><b>Защита от злоупотреблений</b><small>Минимальный чек и ограничения</small></span><ChevronDown/></summary><div className="referral-form-grid"><label>Минимальная сумма покупки, ₸<input type="number" min="0" value={program.minimumPurchaseAmount} onChange={e=>update({minimumPurchaseAmount:Number(e.target.value)})}/><small>Покупки ниже суммы не учитываются</small></label><label>Задержка начисления, дней<input type="number" min="0" max="365" value={program.rewardDelayDays} onChange={e=>update({rewardDelayDays:Number(e.target.value)})}/><small>Время на проверку возможного возврата</small></label><label>Приглашений от одного клиента в месяц<input type="number" min="0" value={program.maxRewardsPerCustomer||0} onChange={e=>update({maxRewardsPerCustomer:Number(e.target.value)||null})}/><small>0 — без ограничения</small></label><label>Успешных приглашений всего в месяц<input type="number" min="0" value={program.maxRewardsPerMonth||0} onChange={e=>update({maxRewardsPerMonth:Number(e.target.value)||null})}/><small>0 — без ограничения</small></label></div></details>
    <InfoCallout title="Ссылка появится автоматически">После запуска каждый клиент увидит в своей карте персональную ссылку и QR для приглашений. <button type="button" onClick={()=>setExampleOpen(true)}>Посмотреть пример</button></InfoCallout>
    <footer><span>{dirty?"Проверьте и сохраните изменения":"Настройки сохранены"}</span><div><button type="submit" value={program.status} disabled={saving||!dirty}>{saving?<LoaderCircle className="spin"/>:<Check/>}Сохранить</button>{program.status==="active"?<button type="submit" value="paused" className="secondary" disabled={saving}><Pause/>Приостановить</button>:<button type="submit" value="active" className="primary" disabled={saving}><Play/>Запустить программу</button>}</div></footer>
   </form><ReferralSummary program={program} stats={stats} money={money}/></div>
   <section className="referral-results"><header><div><h2>Результаты</h2><p>Путь клиентов от открытия ссылки до начисления бонуса.</p></div>{stats.clicks>0&&<StatusBadge tone="success">{stats.conversionRate.toFixed(1)}% зарегистрировались</StatusBadge>}</header>{stats.clicks===0?<EmptyState icon={Link2} title="Рекомендаций пока нет" description="После запуска здесь появятся переходы, регистрации и первые покупки."/>:<div className="referral-result-row"><span><small>Открыли ссылку</small><strong>{stats.clicks}</strong></span><span><small>Зарегистрировались</small><strong>{stats.registrations}</strong></span><span><small>Совершили покупку</small><strong>{stats.qualified}</strong></span><span><small>Получили бонус</small><strong>{stats.rewarded}</strong></span></div>}</section>
   {stats.leaders.length>0&&<section className="referral-leaders"><header><Trophy/><div><h2>Клиенты, которые рекомендуют чаще</h2><p>По успешным приглашениям</p></div></header>{stats.leaders.map((item,index)=><article key={item.customerId}><b>{index+1}</b><span><strong>{item.name||"Клиент"}</strong><small>{item.invited} приглашений · {money(item.revenue)}</small></span></article>)}</section>}
   {exampleOpen&&<div className="referral-example-bg" onMouseDown={e=>{if(e.target===e.currentTarget)setExampleOpen(false)}}><section role="dialog" aria-modal="true" aria-labelledby="referral-example-title"><header><div><small>ПРИМЕР ДЛЯ КЛИЕНТА</small><h2 id="referral-example-title">Пригласить друга</h2></div><button onClick={()=>setExampleOpen(false)} aria-label="Закрыть"><X/></button></header><div className="referral-example-code"><QrCode/><strong>Моя персональная ссылка</strong><code>tappix.app/r/MADINA</code></div><button onClick={async()=>{await navigator.clipboard.writeText("Приглашаю вас в Dentline — после первой покупки мы оба получим бонусы!");setExampleOpen(false);setMessage("Текст приглашения скопирован")}}><Copy/>Скопировать текст для WhatsApp</button></section></div>}
  </>}
 </SectionShell>
}

function ReferralFlow({referrer,friend}:{referrer:number;friend:number}){return <section className="referral-flow" aria-label="Как работает реферальная программа"><article><span><UserRound/></span><strong>Мадина</strong><small>делится ссылкой</small></article><ArrowDown/><article><span><UserRound/></span><strong>Алина</strong><small>регистрируется</small></article><ArrowDown/><article><span><ShoppingBag/></span><strong>Первая покупка</strong><small>подтверждена</small></article><ArrowDown/><article className="reward"><span><Gift/></span><strong>Бонус получают обе</strong><small>Мадина +{referrer} · Алина +{friend}</small></article></section>}
function ReferralSummary({program,stats,money}:{program:Program;stats:Analytics;money:(n:number)=>string}){const total=program.referrerRewardValue+program.friendRewardValue;return <aside className="referral-live-summary"><small>ТАК БУДЕТ РАБОТАТЬ</small><h2>Мадина приглашает Алину</h2><p>После первой покупки от {money(program.minimumPurchaseAmount)}:</p><div><span><UserRound/><small>Мадина</small><strong>+{program.referrerRewardValue} бонусов</strong></span><span><UserRound/><small>Алина</small><strong>+{program.friendRewardValue} бонусов</strong></span></div><dl><div><dt>Пример расходов за 10 приглашений</dt><dd>{money(total*10)}</dd></div><div><dt>Приглашённым</dt><dd>{money(program.friendRewardValue*10)}</dd></div><div><dt>Пригласившим</dt><dd>{money(program.referrerRewardValue*10)}</dd></div></dl>{stats.revenue>0&&<div className="referral-roi"><span>Выручка по рекомендациям</span><strong>{money(stats.revenue)}</strong><small>Стоимость выданных бонусов: {money(stats.rewardCost)}</small></div>}</aside>}
