"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Copy, Gift, Link2, LoaderCircle, Pause, Play, QrCode, ShieldCheck, Sparkles, TrendingUp, Trophy, UserPlus, UsersRound, WalletCards } from "lucide-react";
import { api } from "@/lib/api";
import { SectionShell } from "./section-shell";

type Program={id:string;name:string;status:"draft"|"active"|"paused";referrerRewardValue:number;friendRewardValue:number;minimumPurchaseAmount:number;rewardDelayDays:number;maxRewardsPerCustomer:number|null;maxRewardsPerMonth:number|null};
type Analytics={clicks:number;registrations:number;qualified:number;rewarded:number;revenue:number;rewardCost:number;conversionRate:number;qualificationRate:number;leaders:{customerId:string;name:string;referralCode:string;invited:number;rewarded:number;revenue:number}[]};
const initial:Program={id:"",name:"Пригласи друга",status:"draft",referrerRewardValue:300,friendRewardValue:200,minimumPurchaseAmount:3000,rewardDelayDays:3,maxRewardsPerCustomer:10,maxRewardsPerMonth:100};

export function ReferralsPage(){
 const[program,setProgram]=useState<Program>(initial),[stats,setStats]=useState<Analytics>({clicks:0,registrations:0,qualified:0,rewarded:0,revenue:0,rewardCost:0,conversionRate:0,qualificationRate:0,leaders:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const[p,a]=await Promise.all([api<Program|null>("/referrals/program"),api<Analytics>("/referrals/analytics")]);if(p)setProgram(p);setStats(a)}catch(error){setMessage(error instanceof Error?error.message:"Не удалось загрузить реферальную программу")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const submitter=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;const status=(submitter?.value||program.status) as Program["status"];try{await api("/referrals/program",{method:"PUT",body:JSON.stringify({...program,status,maxRewardsPerCustomer:program.maxRewardsPerCustomer||null,maxRewardsPerMonth:program.maxRewardsPerMonth||null})});setProgram(value=>({...value,status}));setMessage(status==="active"?"Программа запущена — ссылка уже доступна клиентам":status==="paused"?"Программа приостановлена":"Изменения сохранены");await load()}catch(error){setMessage(error instanceof Error?error.message:"Не удалось сохранить программу")}finally{setSaving(false)}}
 const money=(value:number)=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"KZT",maximumFractionDigits:0}).format(value);
 const ratio=stats.rewardCost?stats.revenue/stats.rewardCost:0;
 return <SectionShell active="/referrals" title="Реферальная программа" subtitle="Превратите постоянных клиентов в амбассадоров">
  {message&&<div className="notice" role="status"><CheckCircle2/>{message}</div>}
  <section className="referral-hero"><div><span><UsersRound/></span><div><small>ПРОГРАММА РЕКОМЕНДАЦИЙ</small><h2>Новый клиент — выгода обоим</h2><p>Друг регистрируется по ссылке, совершает первую покупку, и только после этого система выдаёт бонусы.</p></div></div><b className={program.status}>{program.status==="active"?"Работает":program.status==="paused"?"На паузе":"Не запущена"}</b></section>
  <div className={`referral-layout ${loading?"is-loading":""}`}><main><form className="referral-program" onSubmit={event=>void save(event)}><header><div><small className="section-kicker">НАСТРОЙКА ЗА 3 ШАГА</small><h2>Условия программы</h2><p>Сразу видно, кто, сколько и после какого действия получит.</p></div><ShieldCheck/></header>
  <section className="referral-step"><b>1</b><div><h3>Как программа называется</h3><p>Это название увидят клиенты в своей карте.</p><label>Название<input name="name" value={program.name} onChange={e=>setProgram({...program,name:e.target.value})} required/></label></div></section>
  <section className="referral-step"><b>2</b><div><h3>Кому и сколько начислить</h3><p>Оба бонуса будут выданы после первой оплаченной покупки друга.</p><div className="referral-rewards"><label><span><Gift/>Постоянному клиенту</span><input name="referrerRewardValue" type="number" min="0" value={program.referrerRewardValue} onChange={e=>setProgram({...program,referrerRewardValue:Number(e.target.value)})}/><small>за приведённого друга</small></label><ArrowRight/><label><span><Sparkles/>Новому клиенту</span><input name="friendRewardValue" type="number" min="0" value={program.friendRewardValue} onChange={e=>setProgram({...program,friendRewardValue:Number(e.target.value)})}/><small>за первую покупку</small></label></div></div></section>
  <section className="referral-step"><b>3</b><div><h3>Защита бюджета</h3><p>Задайте минимальный чек и лимиты. Ноль означает «без лимита».</p><div className="referral-form-grid"><label>Минимальный чек, ₸<input name="minimumPurchaseAmount" type="number" min="0" value={program.minimumPurchaseAmount} onChange={e=>setProgram({...program,minimumPurchaseAmount:Number(e.target.value)})}/><small>Покупки ниже суммы не учитываются</small></label><label>Начислить через, дней<input name="rewardDelayDays" type="number" min="0" max="365" value={program.rewardDelayDays} onChange={e=>setProgram({...program,rewardDelayDays:Number(e.target.value)})}/><small>Время на проверку возврата</small></label><label>На одного клиента<input name="maxRewardsPerCustomer" type="number" min="0" value={program.maxRewardsPerCustomer||0} onChange={e=>setProgram({...program,maxRewardsPerCustomer:Number(e.target.value)||null})}/><small>Максимум успешных приглашений</small></label><label>На всю программу в месяц<input name="maxRewardsPerMonth" type="number" min="0" value={program.maxRewardsPerMonth||0} onChange={e=>setProgram({...program,maxRewardsPerMonth:Number(e.target.value)||null})}/><small>Общий месячный предел</small></label></div></div></section>
  <footer><span><WalletCards/><small>Стоимость одного успешного приглашения</small><strong>{program.referrerRewardValue+program.friendRewardValue} бонусов</strong></span><div><button name="status" value={program.status} disabled={saving}>{saving?<LoaderCircle className="spin"/>:<CheckCircle2/>}Сохранить</button>{program.status==="active"?<button name="status" value="paused" className="pause" disabled={saving}><Pause/>На паузу</button>:<button name="status" value="active" className="launch" disabled={saving}><Play/>Запустить</button>}</div></footer></form>
  <section className="referral-funnel"><header><div><h2>Как работает программа</h2><p>Путь клиента от ссылки до начисления.</p></div><span>{stats.conversionRate.toFixed(1)}% конверсия</span></header><div><article><Link2/><strong>{stats.clicks}</strong><small>Открыли ссылку</small></article><ArrowRight/><article><UserPlus/><strong>{stats.registrations}</strong><small>Зарегистрировались</small></article><ArrowRight/><article><CheckCircle2/><strong>{stats.qualified}</strong><small>Купили впервые</small></article><ArrowRight/><article><Gift/><strong>{stats.rewarded}</strong><small>Получили бонус</small></article></div></section></main><aside><section className="referral-economics"><header><TrendingUp/><span><small>РЕЗУЛЬТАТ ПРОГРАММЫ</small><strong>{money(stats.revenue)}</strong></span></header><div><span>Выручка от рекомендаций <b>{money(stats.revenue)}</b></span><span>Стоимость бонусов <b>{money(stats.rewardCost)}</b></span><span>Возврат на 1 ₸ <b>{ratio.toFixed(1)}×</b></span><span>Дошли до покупки <b>{stats.qualificationRate.toFixed(1)}%</b></span></div></section><section className="referral-share-preview"><span><QrCode/></span><h3>Клиенту ничего настраивать не нужно</h3><p>Персональная ссылка и QR уже находятся в его карте. Остаётся нажать «Пригласить друга».</p><button onClick={async()=>{await navigator.clipboard.writeText("Приглашаю вас в программу лояльности — получите бонус после первой покупки!");setMessage("Текст приглашения скопирован")}}><Copy/>Скопировать текст WhatsApp</button></section><section className="ambassador-list"><header><Trophy/><div><h3>Амбассадоры</h3><p>Клиенты с успешными приглашениями</p></div></header>{stats.leaders.length?stats.leaders.map((item,index)=><article key={item.customerId}><b>{index+1}</b><span><strong>{item.name||"Клиент"}</strong><small>{item.invited} приглашений · {money(item.revenue)}</small></span></article>):<div><Trophy/><strong>Пока нет данных</strong><p>Здесь появятся клиенты после первой покупки по приглашению.</p></div>}</section></aside></div>
 </SectionShell>
}
