"use client";
import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Eye, RefreshCw, ShieldAlert, ShieldCheck, X } from "lucide-react";
import { api } from "@/lib/api";
import { SectionShell } from "./section-shell";
import { useDialogFocusTrap } from "./use-dialog-focus-trap";

type Risk={id:string;operation:string;ruleCode:string;severity:"warning"|"blocked";status:string;reason:string;createdAt:string;customer:string;phone:string;branch:string;actor:string;resolution:string;metadata:Record<string,unknown>};
type Result={items:Risk[];summary:{open:number;blocked:number;reviewed30Days:number}};
const ruleNames:Record<string,string>={duplicate_operation:"Повтор операции",rapid_visit:"Слишком частый визит",large_manual_adjustment:"Крупная ручная корректировка",behavior_anomaly:"Необычное поведение"};

export function RiskCenterPage(){
 const[data,setData]=useState<Result|null>(null),[status,setStatus]=useState("open"),[severity,setSeverity]=useState(""),[selected,setSelected]=useState<Risk|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const dialog=useDialogFocusTrap<HTMLFormElement>(Boolean(selected),()=>setSelected(null));
 function load(){setLoading(true);setMessage("");return api<Result>(`/risk-investigations?status=${status}&severity=${severity}`).then(setData).catch(error=>setMessage(error instanceof Error?error.message:"Не удалось загрузить расследования")).finally(()=>setLoading(false))}
 useEffect(()=>{void load()},[status,severity]);
 async function decide(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);setSaving(true);setMessage("");try{await api(`/risk-investigations/${selected.id}/decision`,{method:"POST",body:JSON.stringify({decision:form.get("decision"),resolution:form.get("resolution")})});setSelected(null);await load()}catch(error){setMessage(error instanceof Error?error.message:"Не удалось закрыть расследование")}finally{setSaving(false)}}
 return <SectionShell active="/risk-center" title="Контроль рисков" subtitle="Подозрительные операции и решения владельца">
  {message&&<div className="risk-error" role="alert">{message}<button onClick={()=>void load()}><RefreshCw/>Повторить</button></div>}
  <section className="risk-overview"><article><span><ShieldAlert/></span><div><small>ОТКРЫТО</small><strong>{data?.summary.open??"—"}</strong><p>требуют проверки</p></div></article><article className="critical"><span><AlertTriangle/></span><div><small>ЗАБЛОКИРОВАНО</small><strong>{data?.summary.blocked??"—"}</strong><p>операция не выполнена</p></div></article><article><span><ShieldCheck/></span><div><small>РАССМОТРЕНО ЗА 30 ДНЕЙ</small><strong>{data?.summary.reviewed30Days??"—"}</strong><p>с решением владельца</p></div></article></section>
  <section className="risk-workspace"><header><div><h2>Очередь расследований</h2><p>Сначала проверяйте заблокированные операции, затем предупреждения.</p></div><div><label>Статус<select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Открытые</option><option value="reviewed">Подтверждённые</option><option value="dismissed">Ложные срабатывания</option><option value="all">Все</option></select></label><label>Критичность<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">Любая</option><option value="blocked">Заблокировано</option><option value="warning">Предупреждение</option></select></label></div></header>
   {loading?<div className="risk-skeleton" aria-label="Загрузка расследований">{[1,2,3].map(x=><i key={x}/>)}</div>:data?.items.length?<div className="risk-list">{data.items.map(item=><article key={item.id}><span className={item.severity}><AlertTriangle/></span><div><small>{ruleNames[item.ruleCode]||item.ruleCode}</small><strong>{item.customer||"Клиент не определён"}</strong><p>{item.reason}</p><footer>{item.branch||"Без филиала"} · {item.actor||"Система"} · {new Date(item.createdAt).toLocaleString("ru-RU")}</footer></div><aside><b className={item.status}>{item.status==="open"?"Нужно решение":item.status==="reviewed"?"Подтверждено":"Ложное"}</b>{item.status==="open"&&<button onClick={()=>setSelected(item)}><Eye/>Рассмотреть</button>}</aside></article>)}</div>:<div className="risk-empty"><ShieldCheck/><h3>Очередь пуста</h3><p>Новых подозрительных операций нет. Tappix продолжает следить за повторами, частыми визитами и крупными корректировками.</p></div>}
  </section>
  {selected&&<div className="risk-dialog-bg" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><form ref={dialog} className="risk-dialog" role="dialog" aria-modal="true" aria-labelledby="risk-title" onSubmit={decide}><header><span><ShieldAlert/></span><button type="button" aria-label="Закрыть" onClick={()=>setSelected(null)}><X/></button></header><small>{ruleNames[selected.ruleCode]||selected.ruleCode}</small><h2 id="risk-title">Принять решение</h2><p>{selected.reason}</p><dl><div><dt>Клиент</dt><dd>{selected.customer||"Не определён"}</dd></div><div><dt>Сотрудник</dt><dd>{selected.actor||"Система"}</dd></div><div><dt>Филиал</dt><dd>{selected.branch||"Не указан"}</dd></div><div><dt>Время</dt><dd>{new Date(selected.createdAt).toLocaleString("ru-RU")}</dd></div></dl><fieldset><legend>Результат проверки</legend><label><input type="radio" name="decision" value="reviewed" defaultChecked/><span><CheckCircle2/><strong>Нарушение подтверждено</strong><small>Событие останется в истории риска.</small></span></label><label><input type="radio" name="decision" value="dismissed"/><span><ShieldCheck/><strong>Ложное срабатывание</strong><small>Операция объяснена и безопасна.</small></span></label></fieldset><label>Комментарий владельца<textarea name="resolution" minLength={6} placeholder="Что проверили и почему приняли это решение" required/></label><footer><button type="button" onClick={()=>setSelected(null)}>Отмена</button><button disabled={saving}>{saving?"Сохраняем…":"Завершить расследование"}</button></footer></form></div>}
 </SectionShell>
}
